package api

type Contract struct {
	Name   string
	Source string
	Params []string
}

var Contracts = []Contract{
	{Name: "apiAIChat", Source: "AIAgent.gs", Params: []string{"token", "period", "selection", "message", "history"}},
	{Name: "apiAIOptions", Source: "AIAgent.gs", Params: []string{"token"}},
	{Name: "apiAccountDelete", Source: "AccountMerge.gs", Params: []string{"token", "nik", "reason"}},
	{Name: "apiAccountDeleteCheck", Source: "AccountMerge.gs", Params: []string{"token", "nik"}},
	{Name: "apiAccountMergeCommit", Source: "AccountMerge.gs", Params: []string{"token", "keep", "drop", "reason"}},
	{Name: "apiAccountMergePreview", Source: "AccountMerge.gs", Params: []string{"token", "keep", "drop"}},
	{Name: "apiActivity", Source: "Activity.gs", Params: []string{"token", "q", "action"}},
	{Name: "apiAddDealer", Source: "DealerImport.gs", Params: []string{"token", "input"}},
	{Name: "apiAdmin", Source: "Admin.gs", Params: []string{"token"}},
	{Name: "apiAdminBanner", Source: "Activity.gs", Params: []string{"token"}},
	{Name: "apiAnalisa", Source: "Analisa.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiBackupSettings", Source: "Backup.gs", Params: []string{"token", "keep", "statusId"}},
	{Name: "apiBootstrap", Source: "Code.gs", Params: []string{"token"}},
	{Name: "apiBrandExportData", Source: "BrandExport.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiBrandExportOptions", Source: "BrandExport.gs", Params: []string{"token"}},
	{Name: "apiChangePin", Source: "Auth.gs", Params: []string{"token", "pin"}},
	{Name: "apiCheckpointRestore", Source: "Activity.gs", Params: []string{"token", "file", "reason"}},
	{Name: "apiCheckpoints", Source: "Activity.gs", Params: []string{"token"}},
	{Name: "apiCommitContactBulk", Source: "DealerContact.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiCommitCustomerBulk", Source: "BulkAdmin.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiCommitDealerTransfer", Source: "BulkAdmin.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiCommitDealers", Source: "DealerImport.gs", Params: []string{"token", "id"}},
	{Name: "apiCommitMasterBulk", Source: "BulkAdmin.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiCommitRestore", Source: "Admin.gs", Params: []string{"token", "id"}},
	{Name: "apiCommitUsers", Source: "Mobile.gs.gs", Params: []string{"token", "id"}},
	{Name: "apiCompare", Source: "Analisa.gs", Params: []string{"token", "period", "selection", "opts"}},
	{Name: "apiContactRequests", Source: "DealerContact.gs", Params: []string{"token", "status"}},
	{Name: "apiCustomerBulkExport", Source: "BulkAdmin.gs", Params: []string{"token"}},
	{Name: "apiDOS", Source: "SellOut.gs", Params: []string{"token", "period", "selection", "filter", "page"}},
	{Name: "apiDOSExportData", Source: "DOSExport.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiDOSExportOptions", Source: "DOSExport.gs", Params: []string{"token"}},
	{Name: "apiDashboard", Source: "Code.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiDealerContact", Source: "DealerContact.gs", Params: []string{"token", "id"}},
	{Name: "apiDealerDelete", Source: "DealerEdit.gs", Params: []string{"token", "uniqs", "reason"}},
	{Name: "apiDealerDeleteCheck", Source: "DealerEdit.gs", Params: []string{"token", "uniq"}},
	{Name: "apiDealerDetail", Source: "Code.gs", Params: []string{"token", "period", "selection", "customer"}},
	{Name: "apiDealerDownloadAll", Source: "DealerUpload.gs", Params: []string{"token"}},
	{Name: "apiDealerEditDetail", Source: "DealerEdit.gs", Params: []string{"token", "uniq"}},
	{Name: "apiDealerHistory", Source: "Code.gs", Params: []string{"token", "selection", "brand", "from", "to", "page", "query", "filters"}},
	{Name: "apiDealerHistorySummary", Source: "Code.gs", Params: []string{"token", "selection", "brand", "from", "to", "query", "filters", "level"}},
	{Name: "apiDealerIndukPeek", Source: "DealerEdit.gs", Params: []string{"token", "uniq", "baru"}},
	{Name: "apiDealerRegionGet", Source: "DealerRegion.gs", Params: []string{"token", "q"}},
	{Name: "apiDealerRegionLookup", Source: "DealerRegion.gs", Params: []string{"token", "dealer"}},
	{Name: "apiDealerRegionSave", Source: "DealerRegion.gs", Params: []string{"token", "op", "reason"}},
	{Name: "apiDealerSave", Source: "DealerEdit.gs", Params: []string{"token", "uniq", "input", "reason"}},
	{Name: "apiDealerSearch", Source: "DealerEdit.gs", Params: []string{"token", "q"}},
	{Name: "apiDealerStock", Source: "Mobile.gs.gs", Params: []string{"token", "period", "selection", "customer"}},
	{Name: "apiDealerTemplate", Source: "DealerTemplate.gs", Params: []string{"token"}},
	{Name: "apiDealerTutupAjukan", Source: "DealerTutup.gs", Params: []string{"token", "id", "tanggal", "alasan"}},
	{Name: "apiDealerTutupList", Source: "DealerTutup.gs", Params: []string{"token"}},
	{Name: "apiDealerTutupProses", Source: "DealerTutup.gs", Params: []string{"token", "row", "aksi", "catatan"}},
	{Name: "apiDealerTutupUpload", Source: "DealerTutup.gs", Params: []string{"token", "rows", "commit"}},
	{Name: "apiDealerUploadCommit", Source: "DealerUpload.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiDealerUploadRejected", Source: "DealerUpload.gs", Params: []string{"token", "id"}},
	{Name: "apiDealerUploadStage", Source: "DealerUpload.gs", Params: []string{"form"}},
	{Name: "apiDemoOptions", Source: "Auth.gs", Params: []string{"token"}},
	{Name: "apiDownloadInfo", Source: "Info.gs", Params: []string{"token", "id"}},
	{Name: "apiEarlyWarning", Source: "Analisa.gs", Params: []string{"token", "period", "level", "brand", "metric", "selection", "filters"}},
	{Name: "apiExec", Source: "Eksekutif.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiExportDealerContacts", Source: "DealerContact.gs", Params: []string{"token"}},
	{Name: "apiExportDealerCsv", Source: "Code.gs", Params: []string{"token", "period", "selection", "filter", "sort"}},
	{Name: "apiExportDealerExcel", Source: "Code.gs", Params: []string{"token", "selection", "from", "to", "filter", "sort"}},
	{Name: "apiExportDealerHistory", Source: "Code.gs", Params: []string{"token", "selection", "brand", "from", "to", "query", "filters"}},
	{Name: "apiExportSummary", Source: "BulkAdmin.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiGrowthType", Source: "Analisa.gs", Params: []string{"token", "period", "selection", "brand", "opts"}},
	{Name: "apiHariLibur", Source: "Analisa.gs", Params: []string{"token"}},
	{Name: "apiHariLiburAdmin", Source: "Analisa.gs", Params: []string{"token"}},
	{Name: "apiHariLiburHapus", Source: "Analisa.gs", Params: []string{"token", "tanggal"}},
	{Name: "apiHariLiburSave", Source: "Analisa.gs", Params: []string{"token", "tanggal", "ket", "aktif"}},
	{Name: "apiHealthCheck", Source: "Health.gs", Params: []string{"token"}},
	{Name: "apiIndukBulkCommit", Source: "DealerEdit.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiIndukBulkRejected", Source: "DealerEdit.gs", Params: []string{"token", "id"}},
	{Name: "apiIndukBulkStage", Source: "DealerEdit.gs", Params: []string{"form"}},
	{Name: "apiIndukBulkTemplate", Source: "DealerEdit.gs", Params: []string{"token"}},
	{Name: "apiInfo", Source: "Info.gs", Params: []string{"token", "page", "query", "region"}},
	{Name: "apiKPIExportData", Source: "KPIExport.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiKPIExportOptions", Source: "KPIExport.gs", Params: []string{"token", "period"}},
	{Name: "apiKpiCopy", Source: "KpiAdmin.gs", Params: []string{"token", "from", "to", "reason"}},
	{Name: "apiKpiGet", Source: "KpiAdmin.gs", Params: []string{"token", "period"}},
	{Name: "apiKpiSaveRegion", Source: "KpiAdmin.gs", Params: []string{"token", "period", "region", "rows", "reason"}},
	{Name: "apiKpiSaveRgm", Source: "KpiAdmin.gs", Params: []string{"token", "period", "nik", "rows", "reason"}},
	{Name: "apiKpiTree", Source: "Code.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiLogin", Source: "Auth.gs", Params: []string{"nik", "pin"}},
	{Name: "apiLogout", Source: "Auth.gs", Params: []string{"token"}},
	{Name: "apiMasterBulkRejected", Source: "BulkAdmin.gs", Params: []string{"token", "id"}},
	{Name: "apiMasterBulkTemplate", Source: "BulkAdmin.gs", Params: []string{"token", "type"}},
	{Name: "apiMyRank", Source: "Code.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiPeriodLock", Source: "Admin.gs", Params: []string{"token", "period", "locked", "reason"}},
	{Name: "apiPersonKpi", Source: "Code.gs", Params: []string{"token", "period", "nik"}},
	{Name: "apiPotensi", Source: "Analisa.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiPublishConfig", Source: "Data.gs", Params: []string{"token"}},
	{Name: "apiPublishImport", Source: "Data.gs", Params: []string{"token", "id"}},
	{Name: "apiPublishSO", Source: "SellOut.gs", Params: []string{"token", "id"}},
	{Name: "apiRank", Source: "Code.gs", Params: []string{"token", "period", "national", "level"}},
	{Name: "apiRankDetail", Source: "Mobile.gs.gs", Params: []string{"token", "period", "nik"}},
	{Name: "apiRegionImportTemplate", Source: "BulkAdmin.gs", Params: []string{"token", "kind"}},
	{Name: "apiRegionMapGet", Source: "RegionMap.gs", Params: []string{"token"}},
	{Name: "apiRegionMapSave", Source: "RegionMap.gs", Params: []string{"token", "input", "reason"}},
	{Name: "apiResetPin", Source: "Auth.gs", Params: []string{"token", "nik"}},
	{Name: "apiReviewDealerContacts", Source: "DealerContact.gs", Params: []string{"token", "ids", "decision", "reason"}},
	{Name: "apiSaveDealerContact", Source: "DealerContact.gs", Params: []string{"token", "input"}},
	{Name: "apiSaveExportAccess", Source: "ExportAccess.gs", Params: []string{"token", "input"}},
	{Name: "apiSaveUser", Source: "Admin.gs", Params: []string{"token", "input"}},
	{Name: "apiSetActive", Source: "Auth.gs", Params: []string{"token", "nik", "isActive"}},
	{Name: "apiSetInfoActive", Source: "Info.gs", Params: []string{"token", "id", "value"}},
	{Name: "apiStageContactBulk", Source: "DealerContact.gs", Params: []string{"form"}},
	{Name: "apiStageCustomerBulk", Source: "BulkAdmin.gs", Params: []string{"form"}},
	{Name: "apiStageDealerTransfer", Source: "BulkAdmin.gs", Params: []string{"form"}},
	{Name: "apiStageDealers", Source: "DealerImport.gs", Params: []string{"form"}},
	{Name: "apiStageImport", Source: "Data.gs", Params: []string{"form"}},
	{Name: "apiStageMasterBulk", Source: "BulkAdmin.gs", Params: []string{"form"}},
	{Name: "apiStageRestore", Source: "Admin.gs", Params: []string{"token", "version", "kind", "period", "regions", "reason"}},
	{Name: "apiStageSO", Source: "SellOut.gs", Params: []string{"form"}},
	{Name: "apiStageUsers", Source: "Mobile.gs.gs", Params: []string{"form"}},
	{Name: "apiStartBackup", Source: "Backup.gs", Params: []string{"token"}},
	{Name: "apiStartDemo", Source: "Auth.gs", Params: []string{"token", "targetNik"}},
	{Name: "apiStatusBulkCommit", Source: "AccountStatus.gs", Params: []string{"token", "id", "reason"}},
	{Name: "apiStatusBulkRejected", Source: "AccountStatus.gs", Params: []string{"token", "id"}},
	{Name: "apiStatusBulkStage", Source: "AccountStatus.gs", Params: []string{"form"}},
	{Name: "apiStopDemo", Source: "Auth.gs", Params: []string{"token"}},
	{Name: "apiSubmitDealerContact", Source: "DealerContact.gs", Params: []string{"token", "input"}},
	{Name: "apiSyncFileDownload", Source: "SyncStatus.gs", Params: []string{"token", "fileId"}},
	{Name: "apiSyncRetry", Source: "SyncStatus.gs", Params: []string{"token", "fileId"}},
	{Name: "apiSyncRunNow", Source: "SyncStatus.gs", Params: []string{"token"}},
	{Name: "apiSyncSchedule", Source: "SyncStatus.gs", Params: []string{"token", "on"}},
	{Name: "apiSyncStatus", Source: "SyncStatus.gs", Params: []string{"token"}},
	{Name: "apiTargetGet", Source: "KpiAdmin.gs", Params: []string{"token", "period", "big", "sub"}},
	{Name: "apiTargetSave", Source: "KpiAdmin.gs", Params: []string{"token", "period", "changes", "reason"}},
	{Name: "apiTeam", Source: "Code.gs", Params: []string{"token", "period", "level", "brand", "selection", "filters"}},
	{Name: "apiTeamComparison", Source: "Weekly.gs", Params: []string{"token", "period", "selection", "request"}},
	{Name: "apiTeamKpi", Source: "Code.gs", Params: []string{"token", "period", "selection"}},
	{Name: "apiTransactionGroups", Source: "Mobile.gs.gs", Params: []string{"token", "period", "selection", "page", "from", "to", "sort", "pageSize"}},
	{Name: "apiTransactions", Source: "Code.gs", Params: []string{"token", "period", "selection", "customer", "page", "dateFrom", "dateTo", "sort", "pageSize"}},
	{Name: "apiTransferDealerTemplate", Source: "BulkAdmin.gs", Params: []string{"token"}},
	{Name: "apiTransferRejected", Source: "BulkAdmin.gs", Params: []string{"token", "id"}},
	{Name: "apiUploadInfo", Source: "Info.gs", Params: []string{"form"}},
	{Name: "apiUserPinExport", Source: "DealerEdit.gs", Params: []string{"token", "gen"}},
	{Name: "apiUserTemplate", Source: "Mobile.gs.gs", Params: []string{"token"}},
	{Name: "apiUsersRejected", Source: "Mobile.gs.gs", Params: []string{"token", "id"}},
	{Name: "apiV6Boot", Source: "Analisa.gs", Params: []string{"token"}},
	{Name: "apiWeeklyAnalysis", Source: "Weekly.gs", Params: []string{"token", "period", "selection", "request"}},
}
