/* Authorization is checked again under the same lock as every mutation. */
function apiAdmin(token){const db=snapshot_(),u=adminGuard_(token,db),superuser=u.role==='SUPER ADMIN',brands=[...new Set(Object.values(db.meta.products||{}).filter(p=>p.device).map(p=>p.brand).filter(Boolean))].sort();return {superuser,url:superuser?book_().getUrl():null,notes:superuser?db.notes:[],regions:RegionCore.regions(db.meta),brands,regionMap:settings_().regions,managedRegions:u.adminRegions||[],periods:db.coverage,processed:db.processed,parts:partitionStatus_(db.parts),users:db.meta.people.filter(p=>p.nik!=='-'&&canManageUser_(u,p)).map(p=>{const a=account_(p.nik);return {...p,active:a?PortalCore.active(a.AKTIF):false,hasPin:!!a?.PIN_HASH};}),bosses:db.meta.people.filter(p=>superuser||['ASM','RGM'].includes(p.role)&&(u.adminRegions||[]).includes(p.wilayah)).map(p=>({nik:p.nik,nama:p.nama,role:p.role,wilayah:p.wilayah})),locks:superuser?optionalTable_('Period_Locks'):[],versions:superuser?optionalTable_('Version_Log').slice(-60).reverse():[],backup:superuser?backupStatus_():null,exportAccess:superuser?exportAccessAdminState_(u):null};}
function partitionStatus_(parts){const out=[];for(const kind of ['ST','SO'])Object.keys(parts?.[kind]||{}).sort().forEach(period=>Object.keys(parts[kind][period]).sort().forEach(region=>out.push({kind,period,region,cutoff:parts[kind][period][region].cutoff})));return out;}
function lastSuper_(db,nik){return db.meta.people.filter(p=>p.role==='SUPER ADMIN'&&p.nik!==nik&&PortalCore.active(account_(p.nik)?.AKTIF)).length===0;}
function readGrid_(name){const s=book_().getSheetByName(name);return s?s.getDataRange().getValues():null;}
function restoreGrid_(name,grid){if(grid)putTable_(name,grid[0],grid.slice(1));}
function apiSaveUser(token,input){adminGuard_(token);const lock=LockService.getScriptLock();lock.waitLock(10000);try{
 const db=snapshot_(),u=adminGuard_(token,db),isSuper=u.role==='SUPER ADMIN',nik=PortalCore.text(input.nik),original=PortalCore.text(input.original),name=PortalCore.text(input.nama),role=PortalCore.text(input.role),region=PortalCore.text(input.region),boss=PortalCore.text(input.atasan),old=db.meta.people.find(p=>p.nik===nik),allowedRoles=isSuper?Object.keys(PortalCore.LEVEL):['SALES','ASM','RGM'];
 if(!/^[A-Za-z0-9._-]{2,60}$/.test(nik)||!name||name.length>120||!allowedRoles.includes(role))throw Error('NIK, nama, atau jabatan tidak valid.');if(original&&original!==nik)throw Error('NIK akun tidak dapat diganti.');if(original&&!old||!original&&old)throw Error('User tidak ditemukan atau NIK sudah terdaftar.');if(old&&!canManageUser_(u,old))throw Error('User di luar kewenangan.');if(nik===u.nik&&(role!==old.role||region!==old.region||boss!==old.atasan))throw Error('Perubahan hak akun sendiri harus dilakukan Super Admin lain.');if(old?.role==='SUPER ADMIN'&&role!=='SUPER ADMIN'&&lastSuper_(db,nik))throw Error('Super Admin aktif terakhir harus dipertahankan.');
 const rm=settings_().regions,willRegion=rm.find(r=>String(r.REGION)===region)?.WILAYAH_KPI||'';if(!isSuper&&!(u.adminRegions||[]).includes(willRegion))throw Error('Region tujuan di luar penugasan.');if(!isSuper&&old&&old.wilayah!==willRegion)throw Error('Perpindahan antar big region melalui Super Admin.');
 if(boss){const b=db.meta.people.find(p=>p.nik===boss);if(!b||PortalCore.LEVEL[b.role]<=PortalCore.LEVEL[role]||b.role==='ADMIN'||(!isSuper&&!canManageUser_(u,b)))throw Error('Atasan harus berada pada jabatan lebih tinggi dalam kewenangan.');}
 const access=Array.isArray(input.adminRegions)?[...new Set(input.adminRegions)]:[];if(role==='ADMIN'&&(!access.length||access.some(r=>!RegionCore.regions(db.meta).includes(r))))throw Error('Pilih wilayah tugas Admin.');const acting=!!input.acting&&['ASM','RGM'].includes(role),portfolio=PortalCore.text(input.portfolio)||region;if(acting&&rm.find(r=>String(r.REGION)===portfolio)?.WILAYAH_KPI!==willRegion)throw Error('Portofolio rangkap harus satu big region.');
 const grids={Master_Sales:readGrid_('Master_Sales'),Admin_Access:readGrid_('Admin_Access'),_Auth:readGrid_('_Auth')},heads=grids.Master_Sales[0],objects=table_('Master_Sales'),source=objects.find(r=>String(r['NIK KARYAWAN'])===nik)||{};let next=objects.filter(r=>String(r['NIK KARYAWAN'])!==nik);next.push({...source,'NIK KARYAWAN':nik,SALES:name,POSISI:role,REGION:region,'NIK ATASAN':boss});if(acting)next.push({...source,'NIK KARYAWAN':nik,SALES:name,POSISI:'SALES',REGION:portfolio,'NIK ATASAN':nik});
 PortalCore.normalize({sales:next,customers:table_('Master_Customer'),products:table_('Master_Product')},settings_());checkpoint_(u.nik,'User '+nik);let pin=null;
 try{putTable_('Master_Sales',heads,next.map(r=>heads.map(h=>r[h]??'')));const rows=optionalTable_('Admin_Access').filter(r=>String(r.NIK)!==nik).map(r=>[r.NIK,r.WILAYAH]);if(role==='ADMIN')access.forEach(r=>rows.push([nik,r]));putTable_('Admin_Access',['NIK','WILAYAH'],rows);if(!old){pin=randomPin_();setPin_(nik,pin,true);}const meta=meta_();validateConfigChange_(db,meta);publish_(meta,db.raw,db.coverage,u.nik,'User '+nik);audit_(u.nik,'SAVE_USER',nik+' '+role);return {nik,pin};}
 catch(e){Object.keys(grids).forEach(n=>restoreGrid_(n,grids[n]));throw e;}
 }finally{lock.releaseLock();}}
function apiPeriodLock(token,period,locked,reason){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const u=guard_(token,true);period=PortalCore.month(period);reason=PortalCore.text(reason);if(reason.length<5||reason.length>500)throw Error('Isi alasan 5–500 karakter.');checkpoint_(u.nik,'Kunci periode '+period);const rows=optionalTable_('Period_Locks').filter(r=>r.PERIODE!==period).map(r=>[r.PERIODE,r.TERKUNCI,r.ALASAN,r.OLEH,r.WAKTU]);rows.push([period,!!locked,reason,u.nik,new Date().toISOString()]);putTable_('Period_Locks',['PERIODE','TERKUNCI','ALASAN','OLEH','WAKTU'],rows);audit_(u.nik,'PERIOD_LOCK',period+' '+!!locked+' '+reason);return true;}finally{lock.releaseLock();}}
function apiStageRestore(token,version,kind,period,regions,reason){const u=guard_(token,true),db=snapshot_();if(!['ST','SO'].includes(kind))throw Error('Jenis data tidak valid.');period=PortalCore.month(period);assertPeriodOpen_(period);regions=parseRegions_(JSON.stringify(regions),db.meta);reason=PortalCore.text(reason);if(reason.length<5)throw Error('Isi alasan pemulihan.');if(!optionalTable_('Version_Log').some(r=>r.SNAPSHOT===version))throw Error('Versi bukan riwayat portal ini.');const past=readJson_(version);if(regions.some(r=>!past.parts?.[kind]?.[period]?.[r]))throw Error('Versi ini tidak memiliki semua partisi yang dipilih.');const entries={},controls=regions.map(r=>{entries[r]=past.parts[kind][period][r];return {region:r,before:summarySO_(db.parts[kind]?.[period]?.[r]?readJson_(db.parts[kind][period][r].file):[]),incoming:summarySO_(readJson_(entries[r].file)),cutoff:entries[r].cutoff};});const id=Utilities.getUuid();props_().setProperty('RESTORE_STAGE_'+id,writeJson_('restore-preview-'+id,{actor:u.nik,created:Date.now(),base:db.id,kind,period,regions,reason,entries}));return {id,controls};}
function apiCommitRestore(token,id){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const u=guard_(token,true),ptr=props_().getProperty('RESTORE_STAGE_'+id);if(!ptr)throw Error('Pratinjau tidak tersedia.');const s=readJson_(ptr),db=snapshot_();if(s.actor!==u.nik||s.base!==db.id||Date.now()-s.created>3600000)throw Error('Data berubah; periksa ulang.');assertPeriodOpen_(s.period);checkpoint_(u.nik,'Pemulihan '+s.reason);const parts=RegionCore.replace(db.parts,s.kind,s.period,s.regions,s.entries),r=publish_(db.meta,db.raw,db.coverage,u.nik,'RESTORE '+s.kind+' '+s.period+' '+s.regions.join(', ')+' '+s.reason,null,parts);props_().deleteProperty('RESTORE_STAGE_'+id);revokeAll_();return r;}finally{lock.releaseLock();}}
