/* Private backup folders. No live session tokens are archived. Resumable batches. */
function digestBlob_(blob){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,blob.getBytes()));}
function backupRoot_(){let id=props_().getProperty('BACKUP_ROOT_ID');if(!id){id=DriveApp.createFolder('Sales Portal - Backup Privat').getId();props_().setProperty('BACKUP_ROOT_ID',id);}return DriveApp.getFolderById(id);}
function backupLog_(status,id,detail){ensureTable_('Backup_Log',['WAKTU','JENIS','STATUS','FOLDER','KETERANGAN'],[]);book_().getSheetByName('Backup_Log').appendRow([new Date().toISOString(),'HARIAN',status,id,String(detail).slice(0,1500)]);}
function backupStatus_(){const log=optionalTable_('Backup_Log'),last=log.filter(r=>r.STATUS==='LENGKAP').slice(-1)[0]||null,job=props_().getProperty('BACKUP_JOB');let secondary=null;try{const id=props_().getProperty('SECONDARY_STATUS_ID');if(id)secondary=JSON.parse(DriveApp.getFileById(id).getBlob().getDataAsString());}catch(e){secondary={status:'Tidak dapat membaca status cadangan kedua'};}return {running:!!job,last,lastEvent:log.slice(-1)[0]||null,overdue:!last||Date.now()-Date.parse(last.WAKTU)>36*3600000,root:props_().getProperty('BACKUP_ROOT_ID'),retention:Number(props_().getProperty('BACKUP_KEEP')||14),secondary};}
function sourceCode_(){const url='https://script.googleapis.com/v1/projects/'+ScriptApp.getScriptId()+'/content',r=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true});if(r.getResponseCode()!==200)throw Error('Backup kode gagal. Aktifkan Google Apps Script API di pengaturan akun, lalu jalankan Pasang autobackup lagi. HTTP '+r.getResponseCode());const code=JSON.parse(r.getContentText());if(!code.files?.some(f=>f.name==='Index'))throw Error('Kode Index tidak ditemukan dalam backup.');return code;}
function allSheets_(){const out={};book_().getSheets().forEach(s=>{out[s.getName()]=s.getDataRange().getValues();});return out;}
function archiveRefs_(db){const refs=new Set();const contact=props_().getProperty('DEALER_CONTACT_STATE');if(contact)refs.add(contact);Object.values(db.raw||{}).forEach(id=>refs.add(id));Object.values(db.so?.raw||{}).forEach(id=>refs.add(id));for(const kind of ['ST','SO'])Object.values(db.parts?.[kind]||{}).forEach(m=>Object.values(m).forEach(e=>refs.add(e.file)));optionalTable_('Informasi').forEach(r=>{if(r.FILE_ID)refs.add(String(r.FILE_ID));});return [...refs];}
function startBackup_(){if(props_().getProperty('BACKUP_JOB'))return;const db=snapshot_(),code=sourceCode_(),dir=backupRoot_().createFolder('Harian-'+new Date().toISOString().replace(/[:.]/g,'-')),secrets={};['PEPPER','ROLE_SCHEMA','APP_SCHEMA','BOOK_ID','FOLDER_ID','DEALER_CONTACT_STATE'].forEach(k=>secrets[k]=props_().getProperty(k));const state={schema:4,started:new Date().toISOString(),owner:Session.getEffectiveUser().getEmail(),status:'BERJALAN',folder:dir.getId(),active:db.id,queue:[db.id,...archiveRefs_(db)],files:[],index:0};
 const save=(name,obj)=>{const blob=Utilities.newBlob(JSON.stringify(obj),'application/json',name),f=dir.createFile(blob);state.files.push({name,copy:f.getId(),sha256:digestBlob_(blob)});};save('master-dan-konfigurasi.json',{sheets:allSheets_(),properties:secrets});save('kode-aplikasi.json',code);const job=dir.createFile('job.json',JSON.stringify(state),'application/json');props_().setProperty('BACKUP_JOB',job.getId());backupLog_('BERJALAN',dir.getId(),'Master, konfigurasi, dan kode sudah disalin.');}
function backupWorker_(){const lock=LockService.getScriptLock();if(!lock.tryLock(1000))return;let state;try{const ptr=props_().getProperty('BACKUP_JOB');if(!ptr)return;const job=DriveApp.getFileById(ptr);state=JSON.parse(job.getBlob().getDataAsString());const dir=DriveApp.getFolderById(state.folder),started=Date.now();let count=0;while(state.index<state.queue.length&&Date.now()-started<180000&&count++<12){const source=state.queue[state.index],blob=DriveApp.getFileById(source).getBlob().setName(source+'.json'),copy=dir.createFile(blob),hash=digestBlob_(blob);if(digestBlob_(copy.getBlob())!==hash)throw Error('Verifikasi salinan gagal.');state.files.push({source,copy:copy.getId(),name:source+'.json',sha256:hash});state.index++;job.setContent(JSON.stringify(state));}
 if(state.index===state.queue.length){state.verifyIndex=state.verifyIndex||0;let verified=0;while(state.verifyIndex<state.files.length&&Date.now()-started<180000&&verified++<12){const f=state.files[state.verifyIndex];if(digestBlob_(DriveApp.getFileById(f.copy).getBlob())!==f.sha256)throw Error('Verifikasi akhir gagal '+f.name);state.verifyIndex++;job.setContent(JSON.stringify(state));}if(state.verifyIndex<state.files.length)return;state.status='LENGKAP';state.finished=new Date().toISOString();dir.createFile('manifest.json',JSON.stringify(state),'application/json');job.setContent(JSON.stringify(state));backupLog_('LENGKAP',state.folder,state.files.length+' file terverifikasi');props_().deleteProperty('BACKUP_JOB');pruneBackups_();}}
 catch(e){backupLog_('GAGAL',state?.folder||'',e.message);props_().deleteProperty('BACKUP_JOB');console.error(e.message);}finally{lock.releaseLock();}}
function dailyBackup_(){const lock=LockService.getScriptLock();lock.waitLock(10000);try{startBackup_();}catch(e){backupLog_('GAGAL','',e.message);throw e;}finally{lock.releaseLock();}backupWorker_();}
function installBackup_(){sourceCode_();ScriptApp.getProjectTriggers().filter(t=>['dailyBackup_','backupWorker_'].includes(t.getHandlerFunction())).forEach(t=>ScriptApp.deleteTrigger(t));ScriptApp.newTrigger('dailyBackup_').timeBased().everyDays(1).atHour(2).inTimezone('Asia/Jakarta').create();ScriptApp.newTrigger('backupWorker_').timeBased().everyMinutes(5).create();props_().setProperty('BACKUP_INSTALLED','1');dailyBackup_();SpreadsheetApp.getUi().alert('Autobackup dipasang oleh akun ini. Periksa status LENGKAP di menu Admin. Pemrosesan dilanjutkan setiap 5 menit bila belum selesai.');}
function pruneBackups_(){const keep=Math.max(2,Math.min(60,Number(props_().getProperty('BACKUP_KEEP')||14))),it=backupRoot_().getFolders(),done=[];while(it.hasNext()){const f=it.next(),m=f.getFilesByName('manifest.json');if(m.hasNext()){try{const v=JSON.parse(m.next().getBlob().getDataAsString());if(v.status==='LENGKAP')done.push({f,at:v.finished});}catch(e){}}}done.sort((a,b)=>b.at.localeCompare(a.at)).slice(keep).forEach(x=>x.f.setTrashed(true));}
function apiStartBackup(token){guard_(token,true);if(props_().getProperty('BACKUP_INSTALLED')!=='1')throw Error('Pasang autobackup melalui menu spreadsheet terlebih dahulu.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{guard_(token,true);startBackup_();return backupStatus_();}finally{lock.releaseLock();}}
function apiBackupSettings(token,keep,statusId){const u=guard_(token,true);keep=Number(keep);if(!Number.isInteger(keep)||keep<2||keep>60)throw Error('Retensi 2–60 backup harian.');if(statusId){const s=JSON.parse(DriveApp.getFileById(String(statusId)).getBlob().getDataAsString());if(s.kind!=='SECONDARY')throw Error('Bukan file status cadangan kedua.');}props_().setProperty('BACKUP_KEEP',String(keep));props_().setProperty('SECONDARY_STATUS_ID',String(statusId||''));audit_(u.nik,'BACKUP_SETTINGS','Retensi '+keep);return backupStatus_();}
/* Emergency recovery is editor-only and restores a NEW spreadsheet, never overwrites live sheets. */
function recoverBackupToNewBook_(){const ui=SpreadsheetApp.getUi(),ask=ui.prompt('Uji / pemulihan backup','ID folder backup harian lengkap. Membuat spreadsheet dan folder data baru; aplikasi aktif tetap.',ui.ButtonSet.OK_CANCEL);if(ask.getSelectedButton()!==ui.Button.OK)return;const dir=DriveApp.getFolderById(ask.getResponseText().trim()),it=dir.getFilesByName('manifest.json');if(!it.hasNext())throw Error('Manifest lengkap tidak ditemukan.');const m=JSON.parse(it.next().getBlob().getDataAsString());if(m.status!=='LENGKAP')throw Error('Backup belum lengkap.');const byName={};m.files.forEach(f=>{const file=DriveApp.getFileById(f.copy);if(digestBlob_(file.getBlob())!==f.sha256)throw Error('Backup rusak: '+f.name);byName[f.name]=file;});const saved=JSON.parse(byName['master-dan-konfigurasi.json'].getBlob().getDataAsString()),book=SpreadsheetApp.create('Sales Portal - Hasil Pemulihan '+new Date().toISOString()),data=DriveApp.createFolder('Sales Portal - Data Pemulihan'),mapping={};m.files.filter(f=>f.source).forEach(f=>{mapping[f.source]=byName[f.name].makeCopy(f.name,data).getId();});const snap=JSON.parse(DriveApp.getFileById(mapping[m.active]).getBlob().getDataAsString());Object.keys(snap.raw||{}).forEach(p=>snap.raw[p]=mapping[snap.raw[p]]);Object.keys(snap.so?.raw||{}).forEach(p=>snap.so.raw[p]=mapping[snap.so.raw[p]]);for(const kind of ['ST','SO'])Object.values(snap.parts?.[kind]||{}).forEach(month=>Object.values(month).forEach(e=>e.file=mapping[e.file]));DriveApp.getFileById(mapping[m.active]).setContent(JSON.stringify(snap));Object.keys(saved.sheets).forEach(name=>{if(['Version_Log','Backup_Log'].includes(name))return;const v=saved.sheets[name],sh=book.insertSheet(name);if(sh.getMaxRows()<v.length)sh.insertRowsAfter(sh.getMaxRows(),v.length-sh.getMaxRows());if(sh.getMaxColumns()<v[0].length)sh.insertColumnsAfter(sh.getMaxColumns(),v[0].length-sh.getMaxColumns());sh.getRange(1,1,v.length,v[0].length).setNumberFormat('@').setValues(v.map(row=>row.map(x=>typeof x==='string'&&/^[=+@]/.test(x)?"'"+x:x)));});book.deleteSheet(book.getSheets()[0]);const info=book.getSheetByName('Informasi');if(info){const v=info.getDataRange().getValues(),col=v[0].indexOf('FILE_ID');if(col>=0){for(let i=1;i<v.length;i++)if(v[i][col])v[i][col]=mapping[v[i][col]]||'';info.getDataRange().setNumberFormat('@').setValues(v);}}const config={...saved.properties,BOOK_ID:book.getId(),FOLDER_ID:data.getId(),INFO_FOLDER_ID:data.getId(),ACTIVE:mapping[m.active]};data.createFile('PROPERTI-PEMULIHAN-RAHASIA.json',JSON.stringify(config),'application/json');byName['kode-aplikasi.json'].makeCopy('kode-aplikasi.json',data);ui.alert('Salinan uji pemulihan siap: '+book.getUrl()+'\nFolder data: '+data.getUrl()+'\nAplikasi aktif belum diubah. Ikuti panduan pemulihan untuk mengaktifkan salinan.');}
