function doGet(){return HtmlService.createHtmlOutputFromFile('Index').setTitle('Sales Portal').addMetaTag('viewport','width=device-width, initial-scale=1');}
function allowed_(db,user,selection){const base=PortalCore.scope(db.meta.people,user.nik);if(!selection||selection==='ALL')return base;if(!base.includes(selection))throw Error('Data di luar cakupan.');return PortalCore.scope(db.meta.people,selection).filter(id=>base.includes(id));}
function apiBootstrap(token){const db=snapshot_(),u=guard_(token,false,false,db),demo=demoState_(token,db),own=PortalCore.scope(db.meta.people,u.nik),me=db.meta.people.find(p=>p.nik===u.nik),ids=u.role==='SALES'&&me?.atasan?db.meta.people.filter(p=>p.nik===me.atasan||p.atasan===me.atasan).map(p=>p.nik):own,exportAccess=demo.active?Object.fromEntries(exportAccessTypeIds_().map(type=>[type,false])):exportAccessForUser_(u);return {user:u,people:db.meta.people.filter(p=>ids.includes(p.nik)),periods:Object.keys(db.coverage).sort().reverse(),processed:db.processed,version:db.id,exportAccess,demo};}
function apiDashboard(token,period,selection){const source=snapshot_(),u=guard_(token,false,false,source),ids=allowed_(source,u,selection),db=coverageView_(source,period,ids,'ST',u),regions=Array.from(new Set(db.meta.people.filter(p=>ids.includes(p.nik)&&p.sales).map(p=>p.wilayah)));const result=PortalCore.report(db,period,ids,regions.length===1?regions[0]:null);result.regionalKpi=regions.map(region=>{const n=ids.filter(id=>db.meta.people.find(p=>p.nik===id)?.wilayah===region);return PortalCore.kpi(db,period,n,region);});const buckets={};ids.forEach(id=>{const p=db.meta.people.find(p=>p.nik===id);if(!p)return;const name=(RegionCore.top(u.role)?p.wilayah:p.portfolio||p.region)||'Lainnya';(buckets[name]=buckets[name]||[]).push(id);});result.regionalBrands=Object.keys(buckets).sort().flatMap(name=>{const team=buckets[name],rows=PortalCore.slice(db,period,team);if(!rows.length&&!team.some(id=>db.meta.people.find(p=>p.nik===id)?.sales))return [];return result.brands.map(b=>({region:name,brand:b.brand,total:PortalCore.metrics(rows,db,period,b.brand),target:PortalCore.target(db.meta,period,team,b.brand,'QTY'),targetDA:PortalCore.target(db.meta,period,team,b.brand,'DA')}));});result.so=StockCore.monthly(db,period,ids);result.total.sellout=result.so.qty;
result.brands.forEach(b=>b.current.sellout=StockCore.monthly(db,period,ids,null,b.brand).qty);
const knownCustomers=new Set(result.customers.map(c=>c.id)),knownTypes=new Set(result.types.map(t=>JSON.stringify([t.brand,t.type])));
(db.stock?.moves||[]).forEach(t=>{if(!t.outQty||t.date.slice(0,7)!==period||t.date>result.so.cutoff||!StockCore.canSee(db,ids,t.customer))return;const product=db.meta.products[t.sku],type=product.type||product.nama||t.sku,tk=JSON.stringify([product.brand,type]);if(!knownTypes.has(tk)){knownTypes.add(tk);result.types.push({brand:product.brand,type,qty:0});}if(!knownCustomers.has(t.customer)){knownCustomers.add(t.customer);const c=db.meta.customers[t.customer];result.customers.push({id:t.customer,nama:c?.nama||t.customer+' (belum di master)',nik:db.stock.owners[t.customer],kota:c?.kota||'',region:c?.region||'',alamat:c?.alamat||'',hp:c?.hp||'',status:'BELUM ORDER',last:null,jeda:null,current:PortalCore.metrics([],db,period),previous:PortalCore.metrics([],db,result.previousPeriod),brands:result.brands.map(b=>({brand:b.brand,...PortalCore.metrics([],db,period,b.brand)}))});}});
result.customers.forEach(c=>{const owner=dealerOwner_(db,c.id,c.nik);c.bigRegion=owner.region||'';c.subRegion=owner.subregion||c.region||'';c.sales=owner.sales||'';c.asm=owner.asm||'';c.current.sellout=StockCore.monthly(db,period,ids,c.id).qty;c.brands.forEach(b=>b.sellout=StockCore.monthly(db,period,ids,c.id,b.brand).qty);});
promotorAttach_(result.customers);
result.regionalBrands.forEach(b=>b.total.sellout=StockCore.monthly(db,period,buckets[b.region],null,b.brand).qty);
result.types.forEach(t=>t.sellout=StockCore.monthly(db,period,ids,null,t.brand,t.type).qty);
result.deviceBrands=[...new Set(Object.values(db.meta.products).filter(p=>p.device).map(p=>p.brand))].sort();
result.brandTotals={target:combinedTarget_(result.brands.map(b=>b.target)),targetDA:combinedTarget_(result.brands.map(b=>b.targetDA)),targetNOO:combinedTarget_(result.brands.map(b=>b.targetNOO))};
result.brandHistory={};result.brands.forEach(b=>{result.brandHistory[b.brand]=result.trend.map(pt=>{const cmp=PortalCore.comparisonPeriod(db,pt.period),qty=PortalCore.metrics(pt.period===period?PortalCore.slice(db,pt.period,ids):PortalCore.sliceCmp(db,pt.period,ids,null,period),db,pt.period,b.brand).qty,previousQty=cmp.available?PortalCore.metrics(PortalCore.sliceCmp(db,cmp.period,ids,cmp.cutoff,period),db,cmp.period,b.brand).qty:null;return {...pt,qty,previousQty,growth:previousQty==null||previousQty===0?null:(qty-previousQty)/previousQty*100};});});result.weeklyPair=weeklyPair_(source,period,ids,u);result.regionStatus=db.regionStatus||[];result.noData=!!db.noData;result.partial=!!db.partial;result.processed=db.processed;result.version=db.id;result.scopeCount=ids.filter(id=>db.meta.people.find(p=>p.nik===id)?.sales).length;return result;}
function apiTeam(token,period,level,brand,selection,filters){
  const source=snapshot_(),u=guard_(token,false,false,source),me=source.meta.people.find(p=>p.nik===u.nik),ids=u.role==='SALES'&&me?.atasan?source.meta.people.filter(p=>p.sales&&p.atasan===me.atasan).map(p=>p.nik):allowed_(source,u,selection),db=coverageView_(source,period,ids,'ST',u),areaLevel=['BIG REGION','REGION'].includes(level);
  if(!['SALES','ASM','RGM','BIG REGION','REGION'].includes(level)||u.role==='SALES'&&level!=='SALES'||!areaLevel&&u.role!=='SALES'&&PortalCore.LEVEL[level]>=PortalCore.LEVEL[u.role])throw Error('Tingkat tim tidak diizinkan.');
  filters=filters||{};const big=String(filters.big||'ALL'),region=String(filters.region||'ALL'),sub=String(filters.sub||'ALL'),sales=db.meta.people.filter(p=>ids.includes(p.nik)&&p.sales).filter(p=>(big==='ALL'||p.wilayah===big)&&(region==='ALL'||(p.portfolio||p.region)===region)&&(sub==='ALL'||(p.portfolio||p.region)===sub)),salesIds=sales.map(p=>p.nik),groups=[];
  if(areaLevel){const buckets={};sales.forEach(p=>{const name=level==='BIG REGION'?(p.wilayah||'LAINNYA'):(p.portfolio||p.region||'LAINNYA');(buckets[name]=buckets[name]||[]).push(p.nik);});Object.keys(buckets).sort((a,b)=>a.localeCompare(b,'id')).forEach(name=>{const first=sales.find(p=>buckets[name].includes(p.nik));groups.push({nik:'AREA:'+name,nama:name,region:level==='BIG REGION'?'Nasional':first?.wilayah||'',role:level,boss:level==='BIG REGION'?'Nasional':first?.wilayah||'—',bossRole:level==='BIG REGION'?'CAKUPAN':'BIG REGION',acting:false,team:buckets[name]});});
  }else db.meta.people.filter(p=>level==='SALES'?salesIds.includes(p.nik):p.role===level&&PortalCore.scope(db.meta.people,p.nik).some(id=>salesIds.includes(id))).forEach(p=>{const team=level==='SALES'?[p.nik]:PortalCore.scope(db.meta.people,p.nik).filter(id=>salesIds.includes(id));let boss=p.role==='ASM'&&level==='SALES'?p:db.meta.people.find(x=>x.nik===p.atasan);groups.push({nik:p.nik,nama:p.nama,region:level==='SALES'?p.portfolio:p.region,role:p.role,boss:boss?boss.nama:'—',bossRole:boss?boss.role:'',acting:level==='SALES'&&p.role!=='SALES',team});});
  const cmp=PortalCore.comparisonPeriod(db,period),output=groups.map(p=>{const team=p.team,curr=PortalCore.metrics(PortalCore.slice(db,period,team),db,period,brand),previous=PortalCore.metrics(PortalCore.sliceCmp(db,cmp.period,team,cmp.cutoff,period),db,cmp.period,brand);curr.sellout=StockCore.monthly(db,period,team,null,brand).qty;return {nik:p.nik,nama:p.nama,region:p.region,role:p.role,boss:p.boss,bossRole:p.bossRole,acting:p.acting,total:curr,previous,previousAvailable:cmp.available,target:PortalCore.target(db.meta,period,team,brand,'QTY'),targetDA:PortalCore.target(db.meta,period,team,brand,'DA'),targetNOO:PortalCore.target(db.meta,period,team,brand,'NOO')};});
 const union=[...new Set(groups.flatMap(p=>p.team))],total=PortalCore.metrics(PortalCore.slice(db,period,union),db,period,brand);total.sellout=StockCore.monthly(db,period,union,null,brand).qty;
 output.push({nik:'',nama:'Total',region:'Seluruh hasil tabel',boss:'',bossRole:'',total,previous:PortalCore.metrics(PortalCore.sliceCmp(db,cmp.period,union,cmp.cutoff,period),db,cmp.period,brand),previousAvailable:cmp.available,target:PortalCore.target(db.meta,period,union,brand,'QTY'),targetDA:PortalCore.target(db.meta,period,union,brand,'DA'),targetNOO:PortalCore.target(db.meta,period,union,brand,'NOO')});return output;
}
function apiRank(token,period,national,level){
 const source=snapshot_(),u=guard_(token,false,false,source);level=level||'SALES';if(!['SALES','ASM'].includes(level))throw Error('Pilih peringkat Sales atau ASM.');
 const ids=PortalCore.scope(source.meta.people,u.nik),db=coverageView_(source,period,national?source.meta.people.map(p=>p.nik):ids,'ST');
 const rows=db.meta.people.filter(p=>p.role===level&&p.nik!=='-'&&(national||ids.includes(p.nik))).map(p=>{
 const team=level==='ASM'?PortalCore.scope(source.meta.people,p.nik):[p.nik],k=PortalCore.kpi(db,period,team,p.wilayah,p),ownCut=source.parts?.ST?.[period]?.[p.wilayah]?.cutoff||null,pending=source.parts?!ownCut:!!db.missingST;
 return {nik:rankDetailAllowed_(source,u,p)?p.nik:null,nama:p.nama,role:level,region:p.region,wilayah:p.wilayah,score:pending?null:k.score,status:pending?'Menunggu ST '+(p.wilayah||'region'):(db.partial||db.missingST?'Sementara · ':'')+k.status+' · s.d. '+(ownCut||db.coverage[period]?.cutoff),groups:k.count,groupScores:k.groups.map(g=>({name:g.name,score:pending?null:g.score,status:pending?'Menunggu ST':g.na?'Tidak diwajibkan':g.pending?'Belum final':g.partial||k.tentative?'Sementara':'Berlaku'})),canOpen:rankDetailAllowed_(source,u,p)};
 }).sort((a,b)=>(b.score??-1)-(a.score??-1)||a.nama.localeCompare(b.nama));
 const VAC=p=>/^VAC/i.test(String(p.nik||''))||/^VACANT\b/i.test(String(p.nama||''));rows.forEach(p=>p.vacant=VAC(p));rows.sort((a,b)=>(a.vacant-b.vacant));const scored=rows.filter(p=>p.score!=null&&!p.vacant);return rows.map(p=>{if(p.vacant)return {...p,rank:null,top:false,bottom:false,achieved:false};const rank=p.score==null?null:scored.filter(x=>x.score>p.score).length+1,bottom=p.score==null?null:scored.filter(x=>x.score<p.score).length+1,top=rank!=null&&rank<=3;return {...p,rank,top,bottom:bottom!=null&&bottom<=3&&!top,achieved:p.score!=null&&p.score>=90};});
}
function apiPersonKpi(token,period,nik){const source=snapshot_(),u=guard_(token,false,false,source),ids=allowed_(source,u,nik),db=coverageView_(source,period,ids,'ST',u),p=db.meta.people.find(p=>p.nik===nik);audit_(u.nik,'DETAIL_KPI',nik);return PortalCore.kpi(db,period,p.role==='SALES'?[nik]:ids,p.wilayah,p);}
function apiTransactions(token,period,selection,customer,page,dateFrom,dateTo,sort,pageSize){
  const source=snapshot_(),u=guard_(token,false,false,source),ids=allowed_(source,u,selection),db=coverageView_(source,period,ids,'ST',u),size=[50,100,200].includes(Number(pageSize))?Number(pageSize):100;PortalCore.month(period);const from=PortalCore.iso(dateFrom||period+'-01'),to=PortalCore.iso(dateTo||db.coverage[period]?.cutoff||PortalCore.end(period));if(from.slice(0,7)!==period||to.slice(0,7)!==period||from>to||to>(db.coverage[period]?.cutoff||PortalCore.end(period)))throw Error('Rentang tanggal harus dalam bulan pilihan, urut, dan tidak melewati cutoff.');
  if(!db.raw[period])return {rows:[],total:0,page:0,pageSize:size,sourceRows:0,totals:{qty:0,amount:0},from,to};
  const raw=readJson_(db.raw[period]).filter(t=>ids.includes(t.nik)&&(!t.region||!db.selectedRegions||db.selectedRegions.includes(t.region))&&(!customer||t.customer===customer)&&t.date>=from&&t.date<=to),all=PortalCore.groupedTransactions(raw,db.meta),requested=Math.max(0,Math.floor(Number(page)||0)),n=Math.min(requested,Math.max(0,Math.ceil(all.length/size)-1));
  sortRecords_(all,sort,[r=>r.date,r=>r.sj,r=>r.nama,r=>r.brand,r=>r.type,r=>r.qty,r=>r.amount]);return {total:all.length,page:n,pageSize:size,from,to,totals:{qty:raw.reduce((n,t)=>n+t.qty,0),amount:PortalCore.round(raw.reduce((n,t)=>n+t.amount,0))},sourceRows:raw.length,rows:all.slice(n*size,n*size+size)};
}

function combinedTarget_(targets){return {exists:targets.length>0&&targets.every(t=>t.exists),value:targets.reduce((s,t)=>s+t.value,0),missing:[...new Set(targets.flatMap(t=>t.missing||[]))]};}

function historyBrandList_(value,brands,label){
 const list=[...new Set((Array.isArray(value)?value:[]).map(PortalCore.text).filter(Boolean))];
 if(list.some(b=>!brands.includes(b)))throw Error(label+' memuat brand yang tidak dikenal.');
 return list;
}
function historyIndicatorList_(value){
 const allowed=['ST','SO','OMZET'],list=[...new Set((Array.isArray(value)?value:[]).map(v=>(PortalCore.text(v)||'').toUpperCase()).filter(Boolean))];
 if(list.some(v=>!allowed.includes(v)))throw Error('Indikator histori tidak dikenal.');
 return list.length?list:allowed.slice();
}
function historySortGetters_(periods,indicators,displayBrands){
 const getters=[r=>r.nama,r=>r.sales,r=>r.region,r=>r.subregion,r=>r.promotor?(r.promFocus?1000:0)+r.promotor.total+1:0,r=>r.gradeText||null],brands=displayBrands||[];
 brands.forEach(brand=>(indicators||['ST','SO','OMZET']).forEach(ind=>{
  const metric=ind==='ST'?'st':ind==='SO'?'so':'omzet',totalKey=ind==='ST'?'totalST':ind==='SO'?'totalSO':'totalOmzet';
  getters.push(...periods.map((p,i)=>r=>r.brandMetrics?.[brand]?.[metric]?.[i]),r=>r.brandMetrics?.[brand]?.[totalKey]);
 }));
 return getters;
}
function dealerOwner_(db,id,nikOverride){
 const c=db.meta.customers[id]||{},people=db.meta.people,owner=people.find(p=>p.nik===(c.nik||nikOverride));let p=owner,asm=null,seen=new Set();
 while(p&&!seen.has(p.nik)){seen.add(p.nik);if(p.role==='ASM'){asm=p;break;}p=people.find(x=>x.nik===p.atasan);}
 return {region:owner?.wilayah||'',subregion:owner?.portfolio||owner?.region||c.region||'',asm:asm?.nama||'',asmNik:asm?.nik||'',sales:owner?.nama||'',salesNik:owner?.nik||''};
}
function historyMode_(value){const mode=(PortalCore.text(value)||'FULL').toUpperCase();if(!['FULL','TODAY','MTD'].includes(mode))throw Error('Cakupan tanggal histori tidak valid.');return mode;}
function historyDateForDay_(period,day){if(!day)return null;const d=Math.min(Number(day),Number(PortalCore.end(period).slice(8)));return period+'-'+String(d).padStart(2,'0');}
function historyWindow_(period,sourceCut,mode,referenceDay){
 if(!sourceCut)return {ready:false,from:null,to:null,sourceCut:null};
 if(mode==='FULL')return {ready:true,from:period+'-01',to:sourceCut,sourceCut};
 const target=historyDateForDay_(period,referenceDay);if(!target||sourceCut<target)return {ready:false,from:mode==='TODAY'?target:period+'-01',to:target,sourceCut};
 return {ready:true,from:mode==='TODAY'?target:period+'-01',to:target,sourceCut};
}
function dealerHistoryData_(token,selection,brand,from,to,query,filters){
 const db=snapshot_(),u=guard_(token,false,false,db),ids=allowed_(db,u,selection);from=PortalCore.month(from);to=PortalCore.month(to);if(from>to)throw Error('Bulan awal harus sebelum/sama dengan bulan akhir.');
 if((Number(to.slice(0,4))-Number(from.slice(0,4)))*12+Number(to.slice(5))-Number(from.slice(5))>23)throw Error('Pilih maksimal 24 bulan agar tabel tetap ringan.');
 const periods=monthSequence_(from,to);if(periods.length>24)throw Error('Pilih maksimal 24 bulan agar tabel tetap ringan.');
 const brands=[...new Set(Object.values(db.meta.products).filter(p=>p.device).map(p=>p.brand))].sort();brand=PortalCore.text(brand)||'ALL';if(brand!=='ALL'&&!brands.includes(brand))throw Error('Brand tidak dikenal.');
 filters=filters||{};let displayBrands=historyBrandList_(filters.displayBrands,brands,'Brand tampilan');if(!displayBrands.length&&brand!=='ALL')displayBrands=[brand];const selectedBrands=displayBrands.length?displayBrands:brands,indicators=historyIndicatorList_(filters.indicators),dateMode=historyMode_(filters.dateMode),basis=filters.basis||'ST',orderBrands=historyBrandList_(filters.orderBrands,brands,'Filter sudah order'),noOrderBrands=historyBrandList_(filters.noOrderBrands,brands,'Filter belum order');
 let order=filters.order?PortalCore.month(filters.order):'',noOrder=filters.noOrder?PortalCore.month(filters.noOrder):'';if(orderBrands.length&&!order)order=to;if(noOrderBrands.length&&!noOrder)noOrder=to;if(!['ST','SO'].includes(basis))throw Error('Acuan filter harus ST atau SO.');
 if([order,noOrder].filter(Boolean).some(p=>!periods.includes(p)))throw Error('Periode order/tidak order harus berada dalam rentang histori.');
 const overlap=orderBrands.filter(b=>noOrderBrands.includes(b));if(overlap.length)throw Error('Brand tidak boleh sekaligus sudah order dan belum order: '+overlap.join(', '));if(order&&noOrder&&order===noOrder&&!orderBrands.length&&!noOrderBrands.length)throw Error('Periode order dan tidak order harus berbeda jika filter multi-brand belum dipilih.');
 const people=db.meta.people.filter(p=>ids.includes(p.nik)&&p.sales),allowedRegions=[...new Set(people.map(p=>p.wilayah).filter(Boolean))].sort(),region=PortalCore.text(filters.region)||'ALL';
 if(region!=='ALL'&&!allowedRegions.includes(region))throw Error('Region di luar cakupan.');
 const allowedSubRegions=[...new Set(people.filter(p=>region==='ALL'||p.wilayah===region).map(p=>p.portfolio||p.region).filter(Boolean))].sort(),subRegion=PortalCore.text(filters.subRegion)||'ALL';
 if(subRegion!=='ALL'&&!allowedSubRegions.includes(subRegion))throw Error('Sub Region di luar cakupan.');
 const scopeRegions=coverageView_(db,to,ids,'ST',u).selectedRegions||allowedRegions,selected=region==='ALL'?scopeRegions.filter(r=>allowedRegions.includes(r)):[region],q=PortalCore.text(query).slice(0,100).toLowerCase();
 const refStCut=db.parts?RegionCore.common(db.parts,'ST',to,selected).cutoff:db.coverage[to]?.cutoff||null,refSoCut=db.parts?RegionCore.common(db.parts,'SO',to,selected).cutoff:db.stock?.coverage?.[to]?.cutoff||null,refStDay=refStCut?Number(refStCut.slice(8)):null,refSoDay=refSoCut?Number(refSoCut.slice(8)):null;
 const calcPeriods=[PortalCore.prev(from),...periods],entries={},get=(id,nik)=>{if(entries[id])return entries[id];const brandCalc={};brands.forEach(b=>brandCalc[b]={st:calcPeriods.map(()=>0),so:calcPeriods.map(()=>0),omzet:calcPeriods.map(()=>0)});const owner=dealerOwner_(db,id,nik);return entries[id]={id,nama:db.meta.customers[id]?.nama||id+' (belum di master)',...owner,stCalc:calcPeriods.map(()=>0),soCalc:calcPeriods.map(()=>0),omzetCalc:calcPeriods.map(()=>0),brandCalc};};
 Object.values(db.meta.customers).filter(c=>ids.includes(c.nik)).forEach(c=>get(c.id,c.nik));
 const calcMonths=calcPeriods.map((p,i)=>{const stSourceCut=db.parts?RegionCore.common(db.parts,'ST',p,selected).cutoff:db.coverage[p]?.cutoff||null,soSourceCut=db.parts?RegionCore.common(db.parts,'SO',p,selected).cutoff:db.stock?.coverage?.[p]?.cutoff||null,stWindow=historyWindow_(p,stSourceCut,dateMode,refStDay),soWindow=historyWindow_(p,soSourceCut,dateMode,refSoDay);
  if(stWindow.ready)PortalCore.slice(db,p,ids,stWindow.to).filter(t=>t.date>=stWindow.from&&(!t.region||selected.includes(t.region))&&brands.includes(t.brand)).forEach(t=>{const row=get(t.customer,t.nik),metric=row.brandCalc[t.brand],match=selectedBrands.includes(t.brand);if(t.q){metric.st[i]+=t.q;if(match)row.stCalc[i]+=t.q;}metric.omzet[i]=PortalCore.round(metric.omzet[i]+(Number(t.a)||0));if(match)row.omzetCalc[i]=PortalCore.round(row.omzetCalc[i]+(Number(t.a)||0));});
  if(soWindow.ready)(db.stock?.moves||[]).filter(t=>t.date.slice(0,7)===p&&t.date>=soWindow.from&&t.date<=soWindow.to&&(!t.region||selected.includes(t.region))&&StockCore.canSee(db,ids,t.customer)).forEach(t=>{const product=db.meta.products[t.sku];if(product?.device&&brands.includes(product.brand)&&t.outQty){const row=get(t.customer,db.stock?.owners?.[t.customer]);row.brandCalc[product.brand].so[i]+=t.outQty;if(selectedBrands.includes(product.brand))row.soCalc[i]+=t.outQty;}});
  return {period:p,stCut:stWindow.ready?stWindow.to:null,soCut:soWindow.ready?soWindow.to:null,stFrom:stWindow.ready?stWindow.from:null,soFrom:soWindow.ready?soWindow.from:null,stSourceCut,soSourceCut,previousPeriod:PortalCore.prev(p)};
 });
 const months=calcMonths.slice(1),sum=values=>values.some(v=>v==null)?null:values.reduce((n,v)=>n+v,0),allRows=Object.values(entries).filter(c=>(!filters.customer||c.id===filters.customer)&&(c.id+' '+c.nama).toLowerCase().includes(q)&&(region==='ALL'||c.region===region)&&(subRegion==='ALL'||c.subregion===subRegion)).sort((a,b)=>a.nama.localeCompare(b.nama)||a.id.localeCompare(b.id));
 allRows.forEach(r=>{calcMonths.forEach((m,i)=>{if(!m.stCut){r.stCalc[i]=null;r.omzetCalc[i]=null;brands.forEach(b=>{r.brandCalc[b].st[i]=null;r.brandCalc[b].omzet[i]=null;});}if(!m.soCut){r.soCalc[i]=null;brands.forEach(b=>r.brandCalc[b].so[i]=null);}});r.st=r.stCalc.slice(1);r.so=r.soCalc.slice(1);r.omzet=r.omzetCalc.slice(1);r.brandMetrics={};r.byBrand={};brands.forEach(b=>{const st=r.brandCalc[b].st.slice(1),so=r.brandCalc[b].so.slice(1),omzet=r.brandCalc[b].omzet.slice(1);r.brandMetrics[b]={st,so,omzet,totalST:sum(st),totalSO:sum(so),totalOmzet:sum(omzet)};r.byBrand[b]=st;});r.totalST=sum(r.st);r.totalSO=sum(r.so);r.totalOmzet=sum(r.omzet);});
 const field=basis==='ST'?'st':'so',at=(r,b,p)=>r.brandMetrics[b][field][periods.indexOf(p)],rows=allRows.filter(r=>(!order||(orderBrands.length?orderBrands.every(b=>at(r,b,order)!=null&&at(r,b,order)>0):r[field][periods.indexOf(order)]!=null&&r[field][periods.indexOf(order)]>0))&&(!noOrder||(noOrderBrands.length?noOrderBrands.every(b=>at(r,b,noOrder)!=null&&at(r,b,noOrder)<=0):r[field][periods.indexOf(noOrder)]!=null&&r[field][periods.indexOf(noOrder)]<=0)));
 const HX=historyAttrApply_(rows,filters||{},selectedBrands);
 return {db,u,periods,calcPeriods,months,calcMonths,brands,brand,displayBrands,selectedBrands,indicators,from,to,basis,dateMode,region,subRegion,regions:allowedRegions,subRegions:allowedSubRegions,order,noOrder,orderBrands,noOrderBrands,sum,rows:HX.rows,promBrand:HX.promBrand,gradeOptions:HX.gradeOptions,prom:PortalCore.text(filters.prom)||'ALL',grade:PortalCore.text(filters.grade)||'ALL'};
}
function historyAggregateRows_(data,rows,withGrowth){
 const growth=(current,previous)=>current==null||previous==null||previous===0?null:(current-previous)/previous*100,out={};
 data.selectedBrands.forEach(b=>{const calc={st:[],so:[],omzet:[]};data.calcMonths.forEach((m,i)=>{['st','so','omzet'].forEach(key=>{const ready=key==='so'?m.soCut:m.stCut;if(!ready){calc[key][i]=null;return;}const vals=rows.map(r=>r.brandCalc[b][key][i]);calc[key][i]=vals.some(v=>v==null)?null:(key==='omzet'?PortalCore.round(vals.reduce((n,v)=>n+v,0)):vals.reduce((n,v)=>n+v,0));});});const item={st:calc.st.slice(1),so:calc.so.slice(1),omzet:calc.omzet.slice(1)};item.totalST=data.sum(item.st);item.totalSO=data.sum(item.so);item.totalOmzet=data.sum(item.omzet);if(withGrowth)item.growth={st:item.st.map((v,i)=>growth(v,calc.st[i])),so:item.so.map((v,i)=>growth(v,calc.so[i])),omzet:item.omzet.map((v,i)=>growth(v,calc.omzet[i]))};out[b]=item;});return out;
}
function historySummaryGroup_(row,level){
 if(level==='BIG')return {key:row.region||'BELUM',label:row.region||'Belum terpetakan',context:''};
 if(level==='REGION')return {key:(row.region||'BELUM')+'\u001f'+(row.subregion||'BELUM'),label:row.subregion||'Belum terpetakan',context:row.region||'Belum terpetakan'};
 if(level==='ASM')return {key:row.asmNik||('ASM:'+String(row.asm||'Belum ada ASM')),label:row.asm||'Belum ada ASM',context:row.region||'Belum terpetakan'};
 return {key:row.salesNik||('SALES:'+String(row.sales||'Belum ada Sales')),label:row.sales||'Belum ada Sales',context:[row.asm,row.subregion||row.region].filter(Boolean).join(' · ')||'Belum terpetakan'};
}
function apiDealerHistorySummary(token,selection,brand,from,to,query,filters,level){
 level=(PortalCore.text(level)||'BIG').toUpperCase();if(!['BIG','REGION','ASM','SALES'].includes(level))throw Error('Level summary histori tidak valid.');
 const data=dealerHistoryData_(token,selection,brand,from,to,query,filters),groups=new Map();
 data.rows.forEach(r=>{const g=historySummaryGroup_(r,level);if(!groups.has(g.key))groups.set(g.key,{key:g.key,label:g.label,context:g.context,rows:[]});groups.get(g.key).rows.push(r);});
 const rows=[...groups.values()].map(g=>({key:g.key,label:g.label,context:g.context,dealerCount:g.rows.length,byBrand:historyAggregateRows_(data,g.rows,false)})).sort((a,b)=>a.label.localeCompare(b.label,'id',{numeric:true,sensitivity:'base'})||a.context.localeCompare(b.context,'id',{numeric:true,sensitivity:'base'}));
 return {level,months:data.months,displayBrands:data.selectedBrands,indicators:data.indicators,totalDealers:data.rows.length,rows,total:{dealerCount:data.rows.length,byBrand:historyAggregateRows_(data,data.rows,true)},filters:{dateMode:data.dateMode,region:data.region,subRegion:data.subRegion,displayBrands:data.displayBrands,indicators:data.indicators}};
}
function apiDealerHistory(token,selection,brand,from,to,page,query,filters){
 const data=dealerHistoryData_(token,selection,brand,from,to,query,filters),{periods,months,brands,rows,sum,selectedBrands}=data;
 sortRecords_(rows,filters?.sort,historySortGetters_(periods,data.indicators,selectedBrands));
 const brandTotals=historyAggregateRows_(data,rows,true);
 const pageSize=[50,100,200].includes(Number(filters?.pageSize))?Number(filters.pageSize):100,n=Math.min(Math.max(0,Math.floor(Number(page)||0)),Math.max(0,Math.ceil(rows.length/pageSize)-1)),publicRow=r=>({id:r.id,nama:r.nama,sales:r.sales,salesNik:r.salesNik,asm:r.asm,asmNik:r.asmNik,region:r.region,subregion:r.subregion,st:r.st,so:r.so,omzet:r.omzet,byBrand:r.byBrand,brandMetrics:r.brandMetrics,totalST:r.totalST,totalSO:r.totalSO,totalOmzet:r.totalOmzet,promotor:r.promotor,promFocus:r.promFocus,grade:r.grade,gradeText:r.gradeText});
 return {months,promBrand:data.promBrand,gradeOptions:data.gradeOptions,promCompare:historyPromCompare_(rows,months),brands,displayBrands:selectedBrands,regions:data.regions,subRegions:data.subRegions,brand:data.brand,from:data.from,to:data.to,filters:{basis:data.basis,dateMode:data.dateMode,region:data.region,subRegion:data.subRegion,displayBrands:data.displayBrands,indicators:data.indicators,order:data.order,noOrder:data.noOrder,orderBrands:data.orderBrands,noOrderBrands:data.noOrderBrands,prom:data.prom,grade:data.grade},total:rows.length,page:n,pageSize,rows:rows.slice(n*pageSize,n*pageSize+pageSize).map(publicRow),totals:{byBrand:brandTotals}};
}

function apiDealerDetail(token,period,selection,customer){
 const source=snapshot_(),u=guard_(token,false,false,source),ids=allowed_(source,u,selection),db=coverageView_(source,period,ids,'ST',u),known=db.meta.customers[customer],history=Object.keys(db.cubes).filter(p=>p<=period).flatMap(p=>PortalCore.slice(db,p,ids)).filter(r=>r.customer===customer),soHistory=(db.stock?.moves||[]).some(t=>t.customer===customer&&t.date.slice(0,7)<=period&&t.outQty&&StockCore.canSee(db,ids,customer));
 if(!(known&&ids.includes(known.nik))&&!history.length&&!soHistory)throw Error('Dealer tidak tersedia dalam cakupan Anda.');
 const rows=PortalCore.slice(db,period,ids).filter(r=>r.customer===customer),brands=[...new Set(Object.values(db.meta.products).map(p=>p.brand))].sort(),current=PortalCore.metrics(rows,db,period),last=history.filter(r=>r.q>0).map(r=>r.date).sort().pop()||null;
 current.sellout=StockCore.monthly(db,period,ids,customer).qty;
 return {id:customer,nama:known?.nama||customer+' (belum di master)',alamat:known?.alamat||'',kota:known?.kota||'',region:known?.region||'',hp:known?.hp||'',last,jeda:last?Math.floor((new Date(db.coverage[period].cutoff)-new Date(last))/86400000):null,status:current.qty>=2?'AKTIF':current.qty>0?'BELUM MINIMUM DA':history.some(r=>r.date.slice(0,7)===PortalCore.prev(period)&&r.q>0)?'DA BULAN LALU':'BELUM ORDER',current,brands:brands.map(brand=>({brand,...PortalCore.metrics(rows,db,period,brand),sellout:StockCore.monthly(db,period,ids,customer,brand).qty}))};
}

function sortRecords_(rows,sort,getters){if(!sort||!Number.isInteger(Number(sort.column))||!getters[Number(sort.column)])return rows;const get=getters[Number(sort.column)],dir=sort.dir==='desc'?-1:1;rows.sort((a,b)=>{const x=get(a),y=get(b);if(x==null||x==='')return y==null||y===''?0:1;if(y==null||y==='')return -1;return dir*(typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'id',{numeric:true,sensitivity:'base'}));});return rows;}

function apiTeamKpi(token,period,selection){
 const source=snapshot_(),u=guard_(token,false,false,source);
 if(!['ASM','RGM','ADMIN','SUPER ADMIN'].includes(u.role)&&!RegionCore.top(u.role))throw Error('Rincian tim KPI tidak tersedia untuk jabatan ini.');
 const ids=allowed_(source,u,selection),chosen=source.meta.people.find(p=>p.nik===selection),admin=['ADMIN','SUPER ADMIN'].includes(u.role),level=RegionCore.top(u.role)||(admin&&!['ASM','RGM','SALES'].includes(chosen?.role))?'ASM':'SALES';
 return source.meta.people.filter(p=>ids.includes(p.nik)&&(level==='ASM'?p.role==='ASM':p.sales)).map(p=>{
 const team=level==='ASM'?PortalCore.scope(source.meta.people,p.nik).filter(id=>ids.includes(id)):[p.nik],db=coverageView_(source,period,team,'ST',u);
 return {nik:p.nik,nama:p.nama,region:p.wilayah||'Belum dipetakan',area:p.portfolio||p.region||'',acting:level==='SALES'&&p.role!=='SALES',kpi:PortalCore.kpi(db,period,team,p.wilayah,p),cutoff:db.coverage[period]?.cutoff||null,partial:!!db.partial,noData:!!db.noData};
 }).sort((a,b)=>a.region.localeCompare(b.region)||a.nama.localeCompare(b.nama));
}

function apiKpiTree(token,period,selection){
 const source=snapshot_(),u=guard_(token,false,false,source);
 if(!['ASM','RGM','ADMIN','SUPER ADMIN'].includes(u.role)&&!RegionCore.top(u.role))throw Error('Rincian tim KPI tidak tersedia untuk jabatan ini.');
 const ids=allowed_(source,u,selection),people=source.meta.people,me=people.find(p=>p.nik===u.nik)||u,top=RegionCore.top(u.role),nodes=[],byId={};
 function node(p,own){const team=own?[p.nik]:PortalCore.scope(people,p.nik).filter(id=>ids.includes(id)),db=coverageView_(source,period,team,'ST',u);return {nik:p.nik,nama:p.nama,role:own?'SALES':p.role,acting:own&&p.role!=='SALES',region:p.wilayah||'Belum dipetakan',area:own?p.portfolio||p.region:p.region,kpi:PortalCore.kpi(db,period,team,p.wilayah,p),cutoff:db.coverage[period]?.cutoff||null,noData:!!db.noData,partial:!!db.partial,children:[]};}
 function peerNode(p){const team=PortalCore.scope(people,p.nik),db=coverageView_(source,period,team,'ST');return {nik:p.nik,nama:p.nama,role:p.role,acting:false,region:p.wilayah||'Belum dipetakan',area:p.region,kpi:PortalCore.kpi(db,period,team,p.wilayah,p),cutoff:db.coverage[period]?.cutoff||null,noData:!!db.noData,partial:!!db.partial,children:[]};}
 const managers=people.filter(p=>ids.includes(p.nik)&&(top?p.role==='ASM':['ASM','RGM'].includes(p.role)));
 managers.forEach(p=>byId[p.nik]=node(p,false));
 function parent(p){const seen=new Set([p.nik]);let id=p.atasan;while(id&&!seen.has(id)){seen.add(id);if(byId[id])return byId[id];id=people.find(x=>x.nik===id)?.atasan;}return null;}
 managers.forEach(p=>{const n=byId[p.nik],boss=top?null:parent(p);(boss?boss.children:nodes).push(n);});
 if(!top)people.filter(p=>ids.includes(p.nik)&&p.sales).forEach(p=>{const n=node(p,true),boss=byId[p.nik]||parent(p);(boss?boss.children:nodes).push(n);});
 if((!selection||selection==='ALL')&&['ASM','RGM'].includes(u.role)){
  people.filter(p=>p.nik!==u.nik&&p.role===u.role&&(u.role==='RGM'||String(p.atasan||'')===String(me.atasan||''))).forEach(p=>nodes.push(peerNode(p)));
 }
 function order(list){list.sort((a,b)=>a.region.localeCompare(b.region)||a.nama.localeCompare(b.nama));list.forEach(n=>order(n.children));}order(nodes);return nodes;
}

function apiMyRank(token,period,selection){
 const source=snapshot_(),u=guard_(token,false,false,source);PortalCore.month(period);
 const nik=selection&&selection!=='ALL'?String(selection):u.nik;if(nik!==u.nik)allowed_(source,u,nik);
 const p=source.meta.people.find(x=>x.nik===nik);if(!p||!['SALES','ASM'].includes(p.role))return {eligible:false,message:'Peringkat individu tersedia untuk Sales dan ASM. Pilih cakupan Sales atau ASM untuk melihat posisinya.'};
 const rows=apiRank(token,period,true,p.role),self=rows.find(x=>x.nik===nik);if(!self)return {eligible:false,message:'Rincian peringkat tidak tersedia dalam izin akun ini.'};
 const regional=rows.filter(x=>x.wilayah===p.wilayah),scored=regional.filter(x=>x.score!=null);
 return {eligible:true,nik,nama:p.nama,role:p.role,region:p.wilayah||'',score:self.score,status:self.status,nationalRank:self.rank,nationalTotal:rows.filter(x=>x.score!=null).length,regionRank:!p.wilayah||self.score==null?null:scored.filter(x=>x.score>self.score).length+1,regionTotal:scored.length};
}

function dealerExportGuard_(token,source){return exportGuard_(token,'DEALER',source);}
function apiExportDealerCsv(token,period,selection,filter,sort){
 const source=snapshot_(),u=dealerExportGuard_(token,source);PortalCore.month(period);allowed_(source,u,selection);
 const report=apiDashboard(token,period,selection),f=filter||{},q=PortalCore.text(f.query).slice(0,100).toLowerCase(),region=PortalCore.text(f.region)||'ALL',subRegion=PortalCore.text(f.subRegion)||'ALL';
 const rows=report.customers.filter(c=>{const b=!f.brand||f.brand==='ALL'?c.current:c.brands.find(b=>b.brand===f.brand)||{qty:0,noo:0};return(c.id+' '+c.nama).toLowerCase().includes(q)&&(!f.status||f.status==='ALL'||c.status===f.status)&&(!f.city||f.city==='ALL'||c.kota===f.city)&&(region==='ALL'||c.bigRegion===region)&&(subRegion==='ALL'||c.subRegion===subRegion)&&(!f.order||f.order==='ALL'||f.order==='YES'&&b.qty>0||f.order==='NO'&&b.qty<=0||f.order==='NEW'&&b.noo>0);}).sort((a,b)=>b.current.qty-a.current.qty);
 sortRecords_(rows,sort,[c=>c.nama,c=>c.bigRegion,c=>c.subRegion,c=>c.status,c=>c.last,...report.brands.map(b=>c=>c.brands.find(x=>x.brand===b.brand)?.qty||0),c=>c.current.qty,c=>c.current.sellout]);
 audit_(u.nik,'DEALER_CSV_EXPORT',period+' '+rows.length+' dealer');return {name:'outlet-'+period+'.csv',rows:[['KODE CUSTOMER','NAMA INDUK CUSTOMER','REGION','SUB REGION','KOTA','STATUS','SELL THRU','OMZET'],...rows.map(c=>[c.id,c.nama,c.bigRegion,c.subRegion,c.kota,c.status,c.current.qty,c.current.omzet])]};
}
function dealerSalesOwner_(db,nik){
 const people=db.meta.people,person=people.find(p=>p.nik===nik);let p=person,asm=null,seen=new Set();
 while(p&&!seen.has(p.nik)){seen.add(p.nik);if(p.role==='ASM'){asm=p;break;}p=people.find(x=>x.nik===p.atasan);}
 return {sales:person?.nama||nik,asm:asm?.nama||'',region:person?.wilayah||'',subregion:person?.portfolio||person?.region||''};
}
function apiExportDealerExcel(token,selection,from,to,filter,sort){
 const source=snapshot_(),u=dealerExportGuard_(token,source),ids=allowed_(source,u,selection);from=PortalCore.month(from);to=PortalCore.month(to);
 if(from>to)throw Error('Bulan awal harus sebelum/sama dengan bulan akhir.');const periods=monthSequence_(from,to);if(periods.length>24)throw Error('Pilih maksimal 24 bulan.');
 const allBrands=[...new Set(Object.values(source.meta.products).filter(p=>p.device).map(p=>p.brand))].sort(),f=filter||{},brands=historyBrandList_(f.brands,allBrands,'Filter brand');if(!brands.length)brands.push(...allBrands);if(!brands.length)throw Error('Brand perangkat belum tersedia.');
 const endDb=coverageView_(source,to,ids,'ST',u),selected=endDb.selectedRegions||[...new Set(source.meta.people.filter(p=>ids.includes(p.nik)&&p.sales).map(p=>p.wilayah).filter(Boolean))],endReport=PortalCore.report(endDb,to,ids),statusById={};endReport.customers.forEach(c=>statusById[c.id]=c);
 const entries={},get=id=>{if(entries[id])return entries[id];const c=source.meta.customers[id]||{},owner=dealerOwner_(source,id,c.nik),metrics={};brands.forEach(b=>metrics[b]={st:0,so:0,omzet:0});return entries[id]={id,nama:c.nama||id+' (belum di master)',kota:c.kota||'',masterRegion:c.region||'',masterNik:c.nik||'',ownerRegion:owner.region||'',ownerSubRegion:owner.subregion||'',metrics,salesIds:new Set(),last:statusById[id]?.last||null,status:statusById[id]?.status||'BELUM ORDER'};};
 Object.values(source.meta.customers).filter(c=>ids.includes(c.nik)).forEach(c=>get(c.id));let stComplete=true,soComplete=true;const monthInfo=[];
 periods.forEach(p=>{const stCut=source.parts?RegionCore.common(source.parts,'ST',p,selected).cutoff:source.coverage[p]?.cutoff||null,soCut=source.parts?RegionCore.common(source.parts,'SO',p,selected).cutoff:source.stock?.coverage?.[p]?.cutoff||null;monthInfo.push({period:p,stCut,soCut});if(!stCut)stComplete=false;if(!soCut)soComplete=false;
  if(stCut)PortalCore.slice(source,p,ids,stCut).filter(t=>(!t.region||selected.includes(t.region))).forEach(t=>{const row=get(t.customer);if((t.q>0||t.a>0)&&t.nik)row.salesIds.add(t.nik);if(brands.includes(t.brand)){row.metrics[t.brand].st+=t.q;row.metrics[t.brand].omzet=PortalCore.round(row.metrics[t.brand].omzet+t.a);}});
  if(soCut)(source.stock?.moves||[]).filter(t=>t.date.slice(0,7)===p&&t.date<=soCut&&(!t.region||selected.includes(t.region))&&StockCore.canSee(source,ids,t.customer)).forEach(t=>{const product=source.meta.products[t.sku];if(product?.device&&brands.includes(product.brand)){const row=get(t.customer);row.metrics[product.brand].so+=t.outQty;}});
 });
 const validStatuses=['AKTIF','BELUM MINIMUM DA','DA BULAN LALU','IDLE','PASIF','BELUM ORDER'],legacyStatus=PortalCore.text(f.status),statuses=[...new Set((Array.isArray(f.statuses)?f.statuses:legacyStatus&&legacyStatus!=='ALL'?[legacyStatus]:[]).map(PortalCore.text).filter(Boolean))];if(statuses.some(s=>!validStatuses.includes(s)))throw Error('Filter status dealer tidak dikenal.');
 const q=PortalCore.text(f.query).slice(0,100).toLowerCase(),city=PortalCore.text(f.city)||'ALL',order=PortalCore.text(f.order)||'ALL',region=PortalCore.text(f.region)||'ALL',subRegion=PortalCore.text(f.subRegion)||'ALL',sum=(row,key)=>brands.reduce((n,b)=>n+row.metrics[b][key],0),isNew=row=>brands.some(b=>{const first=source.first[PortalCore.key([row.id,b])];return first&&first.date.slice(0,7)>=from&&first.date.slice(0,7)<=to&&ids.includes(first.nik);});
 let rows=Object.values(entries).filter(r=>(r.id+' '+r.nama).toLowerCase().includes(q)&&(!statuses.length||statuses.includes(r.status))&&(city==='ALL'||r.kota===city)&&(region==='ALL'||r.ownerRegion===region)&&(subRegion==='ALL'||r.ownerSubRegion===subRegion)&&(order==='ALL'||order==='YES'&&sum(r,'st')>0||order==='NO'&&sum(r,'st')<=0||order==='NEW'&&isNew(r)));
 const ATX=attrExportApply_(rows,f);rows=ATX.rows;
 rows.forEach(r=>{if(!r.salesIds.size&&r.masterNik)r.salesIds.add(r.masterNik);const owners=[...r.salesIds].map(id=>dealerSalesOwner_(source,id)),unique=a=>[...new Set(a.filter(Boolean))].sort().join(', ');r.sales=unique(owners.map(x=>x.sales));r.asm=unique(owners.map(x=>x.asm));r.region=unique(owners.map(x=>x.region))||r.ownerRegion;r.subregion=unique(owners.map(x=>x.subregion))||r.ownerSubRegion||r.masterRegion;r.totalST=stComplete?sum(r,'st'):null;r.totalSO=soComplete?sum(r,'so'):null;r.totalOmzet=stComplete?sum(r,'omzet'):null;if(!stComplete)brands.forEach(b=>{r.metrics[b].st=null;r.metrics[b].omzet=null;});if(!soComplete)brands.forEach(b=>r.metrics[b].so=null);delete r.salesIds;delete r.masterNik;delete r.masterRegion;delete r.ownerRegion;delete r.ownerSubRegion;});
 rows.sort((a,b)=>a.region.localeCompare(b.region)||a.subregion.localeCompare(b.subregion)||a.asm.localeCompare(b.asm)||a.sales.localeCompare(b.sales)||a.status.localeCompare(b.status)||a.nama.localeCompare(b.nama)||a.id.localeCompare(b.id));
 const selectedPerson=selection&&selection!=='ALL'?source.meta.people.find(p=>p.nik===selection):null,scope=selectedPerson?(selectedPerson.role+' · '+selectedPerson.nama):(RegionCore.top(u.role)||u.role==='SUPER ADMIN'?'NASIONAL':u.role==='ADMIN'?(u.adminRegions||[]).join(', ')||'CAKUPAN ADMIN':u.role+' · '+u.nama),regions=[...new Set(rows.flatMap(r=>String(r.region||'').split(', ')).filter(Boolean))].sort(),subRegions=[...new Set(rows.flatMap(r=>String(r.subregion||'').split(', ')).filter(Boolean))].sort();
 audit_(u.nik,'DEALER_XLSX_EXPORT',from+'..'+to+' '+rows.length+' dealer '+brands.join('|'));return {name:'Daftar-Dealer-'+from+'_sd_'+to+'.xlsx',periods,months:monthInfo,brands,filters:{from,to,scope,regions,subRegions,region,subRegion,query:PortalCore.text(f.query),statuses,order,city,brands,count:rows.length,stComplete,soComplete,prom:PortalCore.text(f.prom)||'ALL',promBrand:PortalCore.text(f.brand)||'ALL',grade:PortalCore.text(f.grade)||'ALL'},gradeBrands:ATX.gradeBrands,rows};
}
function apiExportDealerHistory(token,selection,brand,from,to,query,filters){
 const source=snapshot_(),u=dealerExportGuard_(token,source),ids=allowed_(source,u,selection);filters=filters||{};const data=dealerHistoryData_(token,selection,brand,from,to,query,filters),requested=historyBrandList_(filters.exportBrands,data.brands,'Brand export'),exportBrands=requested.length?requested:data.selectedBrands,summaryLevel=(PortalCore.text(filters.summaryLevel)||'BIG').toUpperCase();if(!['BIG','REGION','ASM','SALES'].includes(summaryLevel))throw Error('Level summary histori tidak valid.');const endDb=coverageView_(source,data.to,ids,'ST',u),statusById={};PortalCore.report(endDb,data.to,ids).customers.forEach(c=>statusById[c.id]=c.status);
 sortRecords_(data.rows,filters?.sort,historySortGetters_(data.periods,data.indicators,data.selectedBrands));
 const addToday=data.dateMode!=='TODAY',todayData=addToday?dealerHistoryData_(token,selection,brand,data.to,data.to,query,{...filters,dateMode:'TODAY',order:'',noOrder:'',orderBrands:[],noOrderBrands:[]}):null,todayRows=new Map((todayData?.rows||[]).map(r=>[r.id,r])),todayByRows=sourceRows=>Object.fromEntries(exportBrands.map(b=>[b,Object.fromEntries(['st','so','omzet'].map(key=>{const ready=todayData?.months?.[0]?.[key==='so'?'soCut':'stCut'];if(!ready)return [key,null];const values=sourceRows.map(r=>todayRows.get(r.id)?.brandMetrics?.[b]?.[key]?.[0]??0),value=values.reduce((n,v)=>n+v,0);return [key,key==='omzet'?PortalCore.round(value):value];}))]));
 const rows=data.rows.map(r=>({id:r.id,nama:r.nama,region:r.region,subregion:r.subregion,asm:r.asm,sales:r.sales,status:statusById[r.id]||'BELUM ORDER',promStatus:r.promotor?'BER-PROMOTOR':'-',promDetail:historyPromDetail_(r),gradeText:r.gradeText||'',brandMetrics:Object.fromEntries(exportBrands.map(b=>[b,r.brandMetrics[b]])),todayMetrics:addToday?todayByRows([r]):null,brands:exportBrands.map(b=>({brand:b,values:r.brandMetrics[b].st.slice(),total:r.brandMetrics[b].totalST,st:r.brandMetrics[b].st.slice(),so:r.brandMetrics[b].so.slice(),omzet:r.brandMetrics[b].omzet.slice(),totalST:r.brandMetrics[b].totalST,totalSO:r.brandMetrics[b].totalSO,totalOmzet:r.brandMetrics[b].totalOmzet}))})).sort((a,b)=>a.region.localeCompare(b.region)||a.subregion.localeCompare(b.subregion)||a.asm.localeCompare(b.asm)||a.sales.localeCompare(b.sales)||a.status.localeCompare(b.status)||a.nama.localeCompare(b.nama)||a.id.localeCompare(b.id));
 const aggregateData={...data,selectedBrands:exportBrands},groups=new Map();data.rows.forEach(r=>{const g=historySummaryGroup_(r,summaryLevel);if(!groups.has(g.key))groups.set(g.key,{key:g.key,label:g.label,context:g.context,rows:[]});groups.get(g.key).rows.push(r);});const summaryRows=[...groups.values()].map(g=>({key:g.key,label:g.label,context:g.context,dealerCount:g.rows.length,byBrand:historyAggregateRows_(aggregateData,g.rows,false),todayByBrand:addToday?todayByRows(g.rows):null})).sort((a,b)=>a.label.localeCompare(b.label,'id',{numeric:true,sensitivity:'base'})||a.context.localeCompare(b.context,'id',{numeric:true,sensitivity:'base'})),summary={level:summaryLevel,rows:summaryRows,total:{dealerCount:data.rows.length,byBrand:historyAggregateRows_(aggregateData,data.rows,true),todayByBrand:addToday?todayByRows(data.rows):null}};
 const selectedPerson=selection&&selection!=='ALL'?source.meta.people.find(p=>p.nik===selection):null,scope=selectedPerson?(selectedPerson.role+' · '+selectedPerson.nama):(RegionCore.top(u.role)||u.role==='SUPER ADMIN'?'NASIONAL':u.role==='ADMIN'?(u.adminRegions||[]).join(', ')||'CAKUPAN ADMIN':u.role+' · '+u.nama),regions=[...new Set(rows.map(r=>r.region).filter(Boolean))].sort(),subRegions=[...new Set(rows.map(r=>r.subregion).filter(Boolean))].sort();audit_(u.nik,'DEALER_HISTORY_XLSX_EXPORT',from+'..'+to+' '+rows.length+' dealer '+exportBrands.join('|'));return {name:'History-Dealer-'+from+'_sd_'+to+'.xlsx',periods:data.periods,months:data.months,brands:exportBrands,indicators:data.indicators,totals:{byBrand:historyAggregateRows_(aggregateData,data.rows,true),todayByBrand:addToday?todayByRows(data.rows):null},summary,filters:{from:data.from,to:data.to,dateMode:data.dateMode,region:data.region,subRegion:data.subRegion,displayBrands:data.displayBrands,indicators:data.indicators,order:data.order,noOrder:data.noOrder,orderBrands:data.orderBrands,noOrderBrands:data.noOrderBrands,exportBrands,summaryLevel,scope,regions,subRegions,query:PortalCore.text(query),count:rows.length,prom:data.prom,grade:data.grade,promBrand:data.promBrand},rows};
}
