/* Dealer creation only: an existing physical dealer is never silently replaced. */
const DEALER_HEADERS=['KODE CUSTOMER','NAMA INDUK CUSTOMER','NIK SALES','ID_DEALER','KOTA','ALAMAT','No. HP','SUB REGION'];
function validateDealers_(rows,db,u){
 if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('Isi 1–500 dealer per unggahan.');
 const codes=new Set(Object.keys(db.meta.customers)),aliases=new Set(Object.values(db.meta.customers).flatMap(c=>c.aliases||[]).filter(Boolean));
 return rows.map((r,i)=>{const clean={};DEALER_HEADERS.forEach(k=>clean[k]=PortalCore.text(r[k]));const id=clean['KODE CUSTOMER'],nik=clean['NIK SALES'],alias=clean.ID_DEALER,p=db.meta.people.find(x=>x.nik===nik);const err=m=>{throw Error('Baris '+(i+2)+': '+m);};
 if(!/^[A-Za-z0-9._-]{1,60}$/.test(id)||!clean['NAMA INDUK CUSTOMER']||clean['NAMA INDUK CUSTOMER'].length>150)err('kode/nama dealer tidak valid.');if(codes.has(id))err('kode dealer sudah terdaftar/berulang: '+id);if(alias&&aliases.has(alias))err('alias ID_DEALER sudah dipakai: '+alias);if(!p?.sales||!canManageUser_(u,p))err('NIK harus Sales atau atasan rangkap dalam wilayah tugas.');if(Object.values(clean).some(v=>v.length>500))err('teks maksimal 500 karakter.');codes.add(id);if(alias)aliases.add(alias);return {...clean,'NAMA CUSTOMER':clean['NAMA INDUK CUSTOMER'],REGION:p.portfolio||p.region,SALES:p.nama};});
}
function dealerReadFile_(file){if(!file?.getBytes||!file.getBytes().length||file.getBytes().length>5*1024*1024)throw Error('Pilih XLSX/CSV maksimal 5 MB.');let grid,tmp;try{if(/\.csv$/i.test(file.getName())){const text=file.getDataAsString('UTF-8').replace(/^\uFEFF/,'');grid=Utilities.parseCsv(text,text.split(/\r?\n/)[0].includes(';')?';':',');}else if(/\.xlsx$/i.test(file.getName())){tmp=Drive.Files.create({name:'DEALER_IMPORT',mimeType:'application/vnd.google-apps.spreadsheet',parents:[folder_().getId()]},file,{fields:'id'}).id;const w=SpreadsheetApp.openById(tmp),sh=w.getSheetByName('Template_Dealer')||w.getSheetByName('Master_Customer')||(w.getSheets().length===1?w.getSheets()[0]:null);if(!sh)throw Error('Sheet Template_Dealer tidak ditemukan.');grid=sh.getDataRange().getDisplayValues();}else throw Error('Gunakan XLSX/CSV.');const heads=(grid.shift()||[]).map(PortalCore.text);DEALER_HEADERS.slice(0,3).forEach(h=>{if(!heads.includes(h))throw Error('Kolom wajib '+h);});return grid.filter(r=>r.some(v=>PortalCore.text(v))).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]])));}finally{if(tmp)DriveApp.getFileById(tmp).setTrashed(true);}}
function apiStageDealers(form){const db=snapshot_(),u=adminGuard_(form.token,db),rows=validateDealers_(dealerReadFile_(form.file),db,u),id=Utilities.getUuid(),s={actor:u.nik,base:db.id,config:configHash_(meta_()),created:Date.now(),rows};props_().setProperty('DEALER_STAGE_'+id,writeJson_('dealer-preview-'+id,s));return {id,total:rows.length,rows:rows.map(r=>({id:r['KODE CUSTOMER'],nama:r['NAMA INDUK CUSTOMER'],nik:r['NIK SALES'],sales:r.SALES,region:r.REGION}))};}
function appendDealers_(rows,db,u){const before=readGrid_('Master_Customer');if(!before)throw Error('Master_Customer tidak ditemukan.');const heads=[...before[0]];[...DEALER_HEADERS,'NAMA CUSTOMER','REGION','SALES'].forEach(h=>{if(!heads.includes(h))heads.push(h);});checkpoint_(u.nik,'Tambah '+rows.length+' dealer');try{putTable_('Master_Customer',heads,before.slice(1).map(r=>heads.map((h,i)=>r[i]??'')).concat(rows.map(r=>heads.map(h=>r[h]??''))));const meta=meta_();validateConfigChange_(db,meta);publish_(meta,db.raw,db.coverage,u.nik,'Tambah '+rows.length+' dealer');return {total:rows.length};}catch(e){restoreGrid_('Master_Customer',before);throw e;}}
function apiCommitDealers(token,id){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const db=snapshot_(),u=adminGuard_(token,db),ptr=props_().getProperty('DEALER_STAGE_'+id);if(!ptr)throw Error('Pratinjau tidak ditemukan.');const s=readJson_(ptr);if(s.actor!==u.nik||s.base!==db.id||s.config!==configHash_(meta_())||Date.now()-s.created>3600000)throw Error('Data berubah/pratinjau kedaluwarsa; periksa file lagi.');const r=appendDealers_(validateDealers_(s.rows,db,u),db,u);props_().deleteProperty('DEALER_STAGE_'+id);return r;}finally{lock.releaseLock();}}
function apiAddDealer(token,input){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const db=snapshot_(),u=adminGuard_(token,db);return appendDealers_(validateDealers_([input],db,u),db,u);}finally{lock.releaseLock();}}
