/* Approved contact overlays and requests commit together via one immutable-state pointer. */
function contactState_(){const id=props_().getProperty('DEALER_CONTACT_STATE');return id?readJson_(id):{requests:[],overrides:{}};}
function saveContactState_(state){const id=writeJson_('dealer-contacts-'+Date.now(),state);props_().setProperty('DEALER_CONTACT_STATE',id);}
function applyDealerContacts_(meta,state){state=state||contactState_();Object.keys(state.overrides).forEach(id=>{if(meta.customers[id])Object.assign(meta.customers[id],state.overrides[id]);});return meta;}
function contactValues_(c){return {pic:String(c.pic||''),hp:String(c.hp||''),alamat:String(c.alamat||'')};}
function contactRegion_(db,c){return db.meta.people.find(p=>p.nik===c.nik)?.wilayah||'';}
function contactCanReview_(db,u,c){return !!c&&(u.role==='SUPER ADMIN'||u.role==='ADMIN'&&(u.adminRegions||[]).includes(contactRegion_(db,c)));}
function contactCanSubmit_(u,c){return !!c&&u.role==='SALES'&&c.nik===u.nik;}
function apiDealerContact(token,id){const db=snapshot_(),u=guard_(token,false,false,db),c=db.meta.customers[id];if(!c||!(PortalCore.scope(db.meta.people,u.nik).includes(c.nik)||contactCanReview_(db,u,c)))throw Error('Dealer di luar cakupan.');const state=contactState_();return {values:contactValues_(c),canSubmit:contactCanSubmit_(u,c),canEdit:contactCanReview_(db,u,c),revision:contactRevision_(db,c),requests:state.requests.filter(r=>r.dealer===id&&(r.actor===u.nik||contactCanReview_(db,u,c))).slice(-20).reverse()};}
function apiSubmitDealerContact(token,input){demoAssertWritable_(token);const lock=LockService.getScriptLock();lock.waitLock(10000);try{demoAssertWritable_(token);const db=snapshot_(),u=guard_(token,false,false,db),c=db.meta.customers[String(input.dealer)];if(!contactCanSubmit_(u,c))throw Error('Hanya Sales pemegang dealer yang dapat mengajukan.');const state=contactState_();if(state.requests.some(r=>r.dealer===c.id&&r.status==='PENDING'))throw Error('Dealer masih memiliki pengajuan menunggu persetujuan.');const before=contactValues_(c);if(JSON.stringify(before)!==JSON.stringify(input.before))throw Error('Kontak berubah. Buka ulang detail dealer.');const after={pic:PortalCore.text(input.pic),hp:PortalCore.text(input.hp),alamat:PortalCore.text(input.alamat)},reason=PortalCore.text(input.reason);if(after.pic.length>120||after.alamat.length>1000||!after.alamat||!after.pic)throw Error('Isi nama PIC (maks.120) dan alamat (maks.1000).');if(!/^[+0-9 ()-]{8,25}$/.test(after.hp)||after.hp.replace(/\D/g,'').length<8||after.hp.replace(/\D/g,'').length>15)throw Error('Nomor HP harus 8–15 digit.');if(reason.length<5||reason.length>500)throw Error('Isi alasan 5–500 karakter.');if(JSON.stringify(before)===JSON.stringify(after))throw Error('Belum ada perubahan.');const row={id:Utilities.getUuid(),dealer:c.id,nama:c.nama,actor:u.nik,actorName:u.nama||db.meta.people.find(p=>p.nik===u.nik)?.nama||u.nik,owner:c.nik,region:contactRegion_(db,c),before,after,reason,status:'PENDING',created:new Date().toISOString()};state.requests.push(row);saveContactState_(state);audit_(u.nik,'CONTACT_SUBMIT',row.id+' '+c.id);return {id:row.id};}finally{lock.releaseLock();}}
function apiContactRequests(token,status){const db=snapshot_(),u=adminGuard_(token,db);return contactState_().requests.filter(r=>{const c=db.meta.customers[r.dealer];return contactCanReview_(db,u,c)&&(!status||status==='ALL'||r.status===status);}).map(r=>{const c=db.meta.customers[r.dealer],stale=!c||r.owner!==c.nik||r.region!==contactRegion_(db,c)||JSON.stringify(r.before)!==JSON.stringify(contactValues_(c));return {...r,stale:r.status==='PENDING'&&stale,current:contactValues_(c||{})};}).reverse();}
function apiReviewDealerContacts(token,ids,decision,reason){if(!Array.isArray(ids)||!ids.length||ids.length>100||new Set(ids).size!==ids.length)throw Error('Pilih 1–100 pengajuan unik.');if(!['APPROVED','REJECTED'].includes(decision))throw Error('Keputusan tidak valid.');reason=PortalCore.text(reason);if(decision==='REJECTED'&&(reason.length<5||reason.length>500))throw Error('Alasan penolakan wajib 5–500 karakter.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const db=snapshot_(),u=adminGuard_(token,db),state=contactState_(),chosen=ids.map(id=>state.requests.find(r=>r.id===id));chosen.forEach(r=>{if(!r||!contactCanReview_(db,u,db.meta.customers[r.dealer]))throw Error('Pengajuan di luar kewenangan.');if(r.status!=='PENDING')throw Error('Pengajuan sudah diproses. Perbarui daftar.');const c=db.meta.customers[r.dealer];if(decision==='APPROVED'&&(r.owner!==c.nik||r.region!==contactRegion_(db,c)||JSON.stringify(r.before)!==JSON.stringify(contactValues_(c))))throw Error('Data berubah: '+r.nama+'. Periksa ulang dan keluarkan dari pilihan.');});chosen.forEach(r=>{r.status=decision;r.reviewed=new Date().toISOString();r.reviewer=u.nik;r.reviewReason=reason;if(decision==='APPROVED')state.overrides[r.dealer]={...r.after};});saveContactState_(state);audit_(u.nik,'CONTACT_'+decision,ids.join(','));return {count:chosen.length};}finally{lock.releaseLock();}}
/* Admin direct edit and Super Admin contact-only replacement. */
function contactRevision_(db,c){return hash_(JSON.stringify({values:contactValues_(c),owner:c.nik,region:contactRegion_(db,c)}));}
function validatedContactUpdate_(input,before){const after={};for(const k of ['pic','hp','alamat'])after[k]=PortalCore.text(input[k])||before[k];if(after.pic.length>120||after.alamat.length>1000)throw Error('Nama PIC maksimal 120, alamat maksimal 1000 karakter.');if(after.hp&&!/^[+0-9 ()-]{8,25}$/.test(after.hp))throw Error('Format nomor HP tidak valid.');const digits=after.hp.replace(/\D/g,'');if(after.hp&&(digits.length<8||digits.length>15))throw Error('Nomor HP harus 8–15 digit.');return after;}
function adminContactRecord_(db,u,c,after,reason,method){return {id:Utilities.getUuid(),dealer:c.id,nama:c.nama,actor:u.nik,actorName:u.nama||db.meta.people.find(p=>p.nik===u.nik)?.nama||u.nik,owner:c.nik,region:contactRegion_(db,c),before:contactValues_(c),after,reason,status:'APPROVED',created:new Date().toISOString(),reviewed:new Date().toISOString(),reviewer:u.nik,reviewReason:method,method};}
function apiSaveDealerContact(token,input){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const db=snapshot_(),u=adminGuard_(token,db),c=db.meta.customers[String(input.dealer)];if(!contactCanReview_(db,u,c))throw Error('Dealer di luar wilayah tugas.');if(input.revision!==contactRevision_(db,c))throw Error('Kontak/pemegang dealer berubah. Buka ulang detail dealer.');const after=validatedContactUpdate_(input,contactValues_(c)),reason=PortalCore.text(input.reason);if(reason.length<5||reason.length>500)throw Error('Isi alasan 5–500 karakter.');if(JSON.stringify(after)===JSON.stringify(contactValues_(c)))throw Error('Tidak ada perubahan.');const state=contactState_(),row=adminContactRecord_(db,u,c,after,reason,'ADMIN_DIRECT');state.requests.push(row);state.overrides[c.id]=after;saveContactState_(state);audit_(u.nik,'CONTACT_ADMIN_EDIT',row.id+' '+c.id);return {id:row.id};}finally{lock.releaseLock();}}
const CONTACT_BULK_HEADERS=['KODE CUSTOMER','NAMA DEALER','REGION','NIK SALES','NAMA PIC','NO HP','ALAMAT','VERSI KONTAK'];
function apiExportDealerContacts(token){const db=snapshot_();guard_(token,true,false,db);return {headers:CONTACT_BULK_HEADERS,rows:Object.values(db.meta.customers).sort((a,b)=>a.nama.localeCompare(b.nama)).map(c=>[c.id,c.nama,contactRegion_(db,c),c.nik,c.pic||'',c.hp||'',c.alamat||'',contactRevision_(db,c)])};}
function contactBulkRows_(file){if(!file?.getBytes||!file.getBytes().length||file.getBytes().length>5*1024*1024)throw Error('Pilih XLSX/CSV maksimal 5 MB.');let grid,tmp;try{if(/\.csv$/i.test(file.getName())){const s=file.getDataAsString('UTF-8').replace(/^\uFEFF/,'');grid=Utilities.parseCsv(s,s.split(/\r?\n/)[0].includes(';')?';':',');}else if(/\.xlsx$/i.test(file.getName())){tmp=Drive.Files.create({name:'CONTACT_IMPORT',mimeType:'application/vnd.google-apps.spreadsheet',parents:[folder_().getId()]},file,{fields:'id'}).id;const w=SpreadsheetApp.openById(tmp),sh=w.getSheetByName('Kontak_Dealer')||(w.getSheets().length===1?w.getSheets()[0]:null);if(!sh)throw Error('Gunakan sheet Kontak_Dealer atau satu sheet saja.');grid=sh.getDataRange().getDisplayValues();}else throw Error('Gunakan XLSX atau CSV.');const heads=(grid.shift()||[]).map(PortalCore.text);['KODE CUSTOMER','NAMA PIC','NO HP','ALAMAT','VERSI KONTAK'].forEach(k=>{if(heads.filter(h=>h===k).length!==1)throw Error('Kolom wajib unik: '+k);});return grid.filter(r=>r.some(v=>PortalCore.text(v))).map(r=>Object.fromEntries(heads.map((h,i)=>[h,PortalCore.text(r[i])])));}finally{if(tmp)DriveApp.getFileById(tmp).setTrashed(true);}}
function validateContactBulk_(rows,db){if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('Isi 1–500 dealer per file.');const seen=new Set();return rows.map((r,i)=>{const id=PortalCore.text(r['KODE CUSTOMER']),c=db.meta.customers[id];if(!c||seen.has(id))throw Error('Kode dealer tidak ditemukan/duplikat di baris '+(i+2));seen.add(id);if(r['VERSI KONTAK']!==contactRevision_(db,c))throw Error('Data berubah atau versi tidak valid: '+c.nama+'. Export ulang.');const before=contactValues_(c),after=validatedContactUpdate_({pic:r['NAMA PIC'],hp:r['NO HP'],alamat:r.ALAMAT},before);return {dealer:id,nama:c.nama,region:contactRegion_(db,c),revision:contactRevision_(db,c),before,after,changed:JSON.stringify(before)!==JSON.stringify(after)};});}
function apiStageContactBulk(form){const db=snapshot_(),u=guard_(form.token,true,false,db),rows=contactBulkRows_(form.file),preview=validateContactBulk_(rows,db),id=Utilities.getUuid();props_().setProperty('CONTACT_BULK_'+id,writeJson_('contact-bulk-preview-'+id,{actor:u.nik,created:Date.now(),rows}));return {id,rows:preview,total:preview.length,changed:preview.filter(r=>r.changed).length};}
function apiCommitContactBulk(token,id,reason){reason=PortalCore.text(reason);if(reason.length<5||reason.length>500)throw Error('Isi alasan 5–500 karakter.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const db=snapshot_(),u=guard_(token,true,false,db),ptr=props_().getProperty('CONTACT_BULK_'+id);if(!ptr)throw Error('Pratinjau tidak tersedia/sudah dipakai.');const stage=readJson_(ptr);if(stage.actor!==u.nik||Date.now()-stage.created>3600000)throw Error('Pratinjau bukan milik akun ini atau kedaluwarsa.');const rows=validateContactBulk_(stage.rows,db).filter(r=>r.changed),state=contactState_();rows.forEach(r=>{const c=db.meta.customers[r.dealer],row=adminContactRecord_(db,u,c,r.after,reason,'SUPER_ADMIN_BULK');state.requests.push(row);state.overrides[r.dealer]=r.after;});if(rows.length)saveContactState_(state);props_().deleteProperty('CONTACT_BULK_'+id);audit_(u.nik,'CONTACT_BULK_REPLACE',id+' '+rows.length);return {updated:rows.length,unchanged:stage.rows.length-rows.length};}finally{lock.releaseLock();}}
