/* DOS export: ASM ke atas, multi-brand, satu brand per sheet. */
function dosExportRoles_(){return ['ASM','RGM','ADMIN','SUPER ADMIN','HEAD OF SALES','CHIEF OPERATING OFFICER','CHIEF COMMERCIAL OFFICER','BOARD OF DIRECTOR'];}
function dosExportGuard_(token,db){return exportGuard_(token,'DOS',db);}
function dosExportSub_(p){return PortalCore.text(p.portfolio||p.region);}
function dosExportAccess_(db,u){
 const people=db.meta.people,sales=people.filter(p=>p.sales),allBig=RegionCore.regions(db.meta),full=['ADMIN','SUPER ADMIN'].includes(u.role)||RegionCore.top(u.role),base=full?people.map(p=>p.nik):PortalCore.scope(people,u.nik),baseSet=new Set(base),salesIds=sales.filter(p=>full||baseSet.has(p.nik)).map(p=>p.nik),salesSet=new Set(salesIds),bigs=full?allBig:(u.wilayah?[u.wilayah]:[]),subs={};
 bigs.forEach(big=>subs[big]=[...new Set(sales.filter(p=>salesSet.has(p.nik)&&p.wilayah===big).map(dosExportSub_).filter(Boolean))].sort());
 return {bigs:[...new Set(bigs)].sort(),subs,salesIds,salesSet};
}
function apiDOSExportOptions(token){
 const db=snapshot_(),u=dosExportGuard_(token,db),access=dosExportAccess_(db,u),brands=brandExportDeviceBrands_(db.meta);return {brands,bigRegions:access.bigs,subParents:access.bigs,subRegions:access.subs,defaultBig:access.bigs.includes(u.wilayah)?u.wilayah:(access.bigs[0]||'')};
}
function dosExportScope_(db,u,selection){
 const access=dosExportAccess_(db,u),people=db.meta.people,level=PortalCore.text(selection.level).toUpperCase();if(!['BIG','SUB'].includes(level))throw Error('Pilih Big Region atau Sub Region.');
 if(level==='BIG'){
  let bigs=brandExportParseList_(selection.bigRegions||[],'Big Region');if(!bigs.length)bigs=access.bigs.slice();if(!bigs.length||bigs.some(r=>!access.bigs.includes(r)))throw Error('Big Region di luar hak akses DOS.');bigs.sort((a,b)=>a.localeCompare(b));const ids=access.salesIds.filter(id=>bigs.includes(people.find(p=>p.nik===id)?.wilayah));if(!ids.length)throw Error('Tidak ada Sales pada cakupan pilihan.');return {level,bigs,subs:[],ids,label:u.role==='ASM'?(PortalCore.text(u.region)||PortalCore.text(u.wilayah)||bigs.join(', ')):bigs.join(', ')};
 }
 const parent=PortalCore.text(selection.parentBig);if(!parent||!access.bigs.includes(parent))throw Error('Big Region induk di luar hak akses DOS.');const known=access.subs[parent]||[];let subs=brandExportParseList_(selection.subRegions||[],'Sub Region');if(!subs.length)subs=known.slice();if(!subs.length||subs.some(r=>!known.includes(r)))throw Error('Sub Region di luar hak akses DOS.');subs.sort((a,b)=>a.localeCompare(b));const ids=access.salesIds.filter(id=>{const p=people.find(x=>x.nik===id);return p?.wilayah===parent&&subs.includes(dosExportSub_(p));});if(!ids.length)throw Error('Tidak ada Sales pada Sub Region pilihan.');return {level,bigs:[parent],subs,ids,label:subs.join(', ')};
}
function dosExportAsm_(people,nik){let p=people.find(x=>x.nik===nik),seen=new Set();while(p&&!seen.has(p.nik)){seen.add(p.nik);if(p.role==='ASM')return p.nama||'';p=people.find(x=>x.nik===p.atasan);}return '';}
function dosExportDealerRows_(db,period,scope,brand){
 const ids=new Set(scope.ids),people=db.meta.people,products=db.meta.products,types=[...new Set(Object.values(products).filter(p=>p.device&&p.brand===brand).map(p=>PortalCore.text(p.type||p.nama||p.id)).filter(Boolean))].sort(),dealers=Object.values(db.meta.customers).filter(c=>ids.has(c.nik)).sort((a,b)=>(a.nama||'').localeCompare(b.nama||'')||a.id.localeCompare(b.id)),dealerSet=new Set(dealers.map(c=>c.id)),asof=db.coverage[period]?.cutoff;if(!asof)throw Error('Cutoff DOS belum tersedia untuk periode pilihan.');const from=StockCore.shift(asof,-29),covered=!!asof&&db.historyComplete!==false&&StockCore.complete(db.coverage,StockCore.BASE,asof)&&StockCore.complete(db.stock?.coverage||{},StockCore.BASE,asof),windowReady=!!from&&from>=StockCore.BASE&&StockCore.complete(db.stock?.coverage||{},from,asof),map={};
 dealers.forEach(c=>{map[c.id]={};types.forEach(type=>map[c.id][type]={type,st:0,so:0,stock:0,so30:0,dos:0,bad:false});});
 (db.stock?.moves||[]).forEach(t=>{if(!dealerSet.has(t.customer)||t.date<StockCore.BASE||t.date>asof)return;const p=products[t.sku];if(!p||!p.device||p.brand!==brand)return;const type=PortalCore.text(p.type||p.nama||t.sku)||'TANPA TYPE';if(!map[t.customer][type]){map[t.customer][type]={type,st:0,so:0,stock:0,so30:0,dos:0,bad:false};if(!types.includes(type))types.push(type);}const x=map[t.customer][type];x.st+=Number(t.inQty)||0;x.so+=Number(t.outQty)||0;if(t.date>=from)x.so30+=Number(t.outQty)||0;});
 types.sort();const calc=x=>{x.stock=x.st-x.so;x.bad=x.stock<0||!covered||!windowReady;x.dos=!x.bad&&x.so30>0?Math.round(x.stock/(x.so30/30)):0;return x;},sumMetrics=items=>{const x={st:0,so:0,stock:0,so30:0,dos:0,bad:false};items.forEach(i=>{x.st+=i.st;x.so+=i.so;x.stock+=i.stock;x.so30+=i.so30;x.bad=x.bad||i.bad;});x.dos=!x.bad&&x.so30>0?Math.round(x.stock/(x.so30/30)):0;return x;};
 const rows=dealers.map(c=>{types.forEach(type=>calc(map[c.id][type]||(map[c.id][type]={type,st:0,so:0,stock:0,so30:0,dos:0,bad:false})));const items=types.map(type=>map[c.id][type]),total=sumMetrics(items),owner=people.find(p=>p.nik===c.nik),note=total.bad?'Perlu cek data':total.stock===0?'Stock 0':'-';return {customer:c.id,nama:c.nama||c.id,sales:owner?.nama||'',asm:dosExportAsm_(people,c.nik),region:dosExportSub_(owner||{})||c.region||'',note,types:items,total};});
 const totalByType=types.map(type=>sumMetrics(rows.map(r=>r.types.find(x=>x.type===type)||{st:0,so:0,stock:0,so30:0,bad:false}))),coverageByType=types.map((type,i)=>{const xs=rows.map(r=>r.types.find(x=>x.type===type)||{st:0,so:0,stock:0,so30:0});return {st:xs.filter(x=>x.st>=2).length,so:xs.filter(x=>x.so>=1).length,stock:xs.filter(x=>x.stock>=1).length,so30:xs.filter(x=>x.so30>=1).length};}),total=sumMetrics(rows.map(r=>r.total)),coverage={st:rows.filter(r=>r.total.st>=2).length,so:rows.filter(r=>r.total.so>=1).length,stock:rows.filter(r=>r.total.stock>=1).length,so30:rows.filter(r=>r.total.so30>=1).length};
 return {brand,types,rows,totalByType,coverageByType,total,coverage,asof,from,covered,windowReady,scopeLabel:scope.label};
}
function apiDOSExportData(token,period,selection){
 const source=snapshot_(),u=dosExportGuard_(token,source);period=PortalCore.month(period);selection=selection&&typeof selection==='object'?selection:{};const scope=dosExportScope_(source,u,selection),known=brandExportDeviceBrands_(source.meta);let brands=brandExportParseList_(selection.brands||[],'Brand');if(!brands.length)brands=known.slice();if(brands.some(b=>!known.includes(b)))throw Error('Brand DOS tidak dikenal.');brands.sort((a,b)=>a.localeCompare(b));const db=coverageView_(source,period,scope.ids,'PAIR',null);if(db.missingST||db.missingSO)throw Error('Menunggu ST dan SO seluruh region dalam pilihan. Pilih cakupan lebih kecil atau lengkapi data.');const sheets=brands.map(brand=>dosExportDealerRows_(db,period,scope,brand));audit_(u.nik,'DOS_XLSX_EXPORT',period+' '+scope.level+' '+scope.label+' '+brands.join('|'));return {name:'DOS-'+period+'-'+scope.level+'.xlsx',period,level:scope.level,scopeLabel:scope.label,asof:db.coverage[period]?.cutoff||null,from:StockCore.shift(db.coverage[period]?.cutoff||period+'-01',-29),sheets};
}
