/* Hak export laporan. ADMIN/SUPER ADMIN mendapat default penuh sampai Super Admin lain menyimpan override per NIK. */
function exportAccessTypes_(){return [{id:'SUMMARY',label:'Ringkasan'},{id:'BRAND',label:'Brand'},{id:'KPI',label:'KPI'},{id:'DOS',label:'DOS'},{id:'DEALER',label:'Dealer'}];}
function exportAccessTypeIds_(){return exportAccessTypes_().map(x=>x.id);}
function exportAccessRows_(){const known=new Set(exportAccessTypeIds_());return optionalTable_('Export_Access').map(r=>({nik:PortalCore.text(r.NIK),type:PortalCore.text(r.JENIS_EXPORT).toUpperCase(),active:PortalCore.active(r.AKTIF)})).filter(r=>r.nik&&known.has(r.type));}
function exportAccessAutomatic_(u){const role=PortalCore.text(u&&u.role).toUpperCase().replace(/\s+/g,' ');return ['ADMIN','SUPER ADMIN'].includes(role);}
function exportAccessForUser_(u,rows){const userRows=(rows||exportAccessRows_()).filter(r=>r.nik===u.nik),granted=userRows.length?new Set(userRows.filter(r=>r.active).map(r=>r.type)):exportAccessAutomatic_(u)?new Set(exportAccessTypeIds_()):new Set(),out={};exportAccessTypeIds_().forEach(type=>out[type]=granted.has(type));return out;}
function exportAccessCanManage_(u,rows){const role=PortalCore.text(u&&u.role).toUpperCase().replace(/\s+/g,' '),access=exportAccessForUser_(u,rows);return role==='SUPER ADMIN'&&exportAccessTypeIds_().every(type=>access[type]);}
function exportGuard_(token,type,db){demoAssertWritable_(token);type=PortalCore.text(type).toUpperCase();if(!exportAccessTypeIds_().includes(type))throw Error('Jenis export tidak valid.');const u=guard_(token,false,false,db);if(!exportAccessForUser_(u)[type])throw Error('Akses export '+type+' belum diberikan oleh Super Admin.');return u;}
function exportAccessAdminState_(actor){const rows=exportAccessRows_(),grants={},configured=[...new Set(rows.map(r=>r.nik))];rows.filter(r=>r.active).forEach(r=>(grants[r.nik]||(grants[r.nik]=[])).push(r.type));Object.keys(grants).forEach(nik=>grants[nik].sort());return {types:exportAccessTypes_(),grants,configured,canManage:exportAccessCanManage_(actor,rows)};}
function apiSaveExportAccess(token,input){const lock=LockService.getScriptLock();lock.waitLock(10000);try{
 const db=snapshot_(),actor=guard_(token,true,false,db),accessRows=exportAccessRows_();if(!exportAccessCanManage_(actor,accessRows))throw Error('Hanya Super Admin utama dengan seluruh hak export yang dapat mengatur izin export.');input=input&&typeof input==='object'?input:{};const nik=PortalCore.text(input.nik),target=db.meta.people.find(p=>p.nik===nik&&p.nik!=='-');if(!target)throw Error('User tidak ditemukan.');if(nik===actor.nik)throw Error('Hak export akun sendiri tidak dapat diubah. Gunakan Super Admin utama lainnya.');
 const known=exportAccessTypeIds_(),types=[...new Set((Array.isArray(input.types)?input.types:[]).map(x=>PortalCore.text(x).toUpperCase()).filter(Boolean))];if(types.some(type=>!known.includes(type)))throw Error('Jenis export tidak valid.');
 const now=new Date().toISOString(),selected=new Set(types),kept=optionalTable_('Export_Access').filter(r=>PortalCore.text(r.NIK)!==nik).map(r=>[r.NIK,r.JENIS_EXPORT,r.AKTIF,r.UPDATED_BY,r.UPDATED_AT]),added=known.map(type=>[nik,type,selected.has(type),actor.nik,now]);putTable_('Export_Access',['NIK','JENIS_EXPORT','AKTIF','UPDATED_BY','UPDATED_AT'],kept.concat(added));audit_(actor.nik,'EXPORT_ACCESS',nik+' '+(types.join('|')||'NONE'));return {nik,types,configured:true};
 }finally{lock.releaseLock();}}
