/* Mobile release: independent KPI permissions; does not expand transaction scope. */
function rankDetailAllowed_(db,u,p){
 if(!p||!['SALES','ASM'].includes(p.role))return false;
 if(u.role==='SUPER ADMIN'||u.role==='RGM'||RegionCore.top(u.role))return true;
 const ids=PortalCore.scope(db.meta.people,u.nik);
 if(u.role==='ADMIN')return ids.includes(p.nik);
 if(u.role==='ASM')return p.role==='ASM'||ids.includes(p.nik);
 if(u.role==='SALES'){const me=db.meta.people.find(x=>x.nik===u.nik);return p.role==='SALES'&&(p.nik===u.nik||!!me?.atasan&&me.atasan===p.atasan&&db.meta.people.some(x=>x.nik===me.atasan&&x.role==='ASM'));}
 return false;
}
function apiRankDetail(token,period,nik){const source=snapshot_(),u=guard_(token,false,false,source),p=source.meta.people.find(x=>x.nik===nik);if(!rankDetailAllowed_(source,u,p))throw Error('Rincian KPI di luar izin peringkat.');const ids=p.role==='ASM'?PortalCore.scope(source.meta.people,nik):[nik],db=coverageView_(source,period,ids,'ST');audit_(u.nik,'RANK_KPI',nik);return {nama:p.nama,role:p.role,region:p.wilayah,kpi:PortalCore.kpi(db,period,ids,p.wilayah,p)};}
function apiTransactionGroups(token,period,selection,page,from,to,sort,pageSize){const source=snapshot_(),u=guard_(token,false,false,source),ids=allowed_(source,u,selection),db=coverageView_(source,period,ids,'ST',u),size=[50,100,200].includes(Number(pageSize))?Number(pageSize):100;PortalCore.month(period);from=PortalCore.iso(from||period+'-01');to=PortalCore.iso(to||db.coverage[period]?.cutoff||PortalCore.end(period));if(from.slice(0,7)!==period||to.slice(0,7)!==period||from>to||to>(db.coverage[period]?.cutoff||PortalCore.end(period)))throw Error('Rentang tanggal tidak valid.');const raw=db.raw[period]?readJson_(db.raw[period]).filter(t=>ids.includes(t.nik)&&(!t.region||!db.selectedRegions||db.selectedRegions.includes(t.region))&&t.date>=from&&t.date<=to):[],groups={};PortalCore.groupedTransactions(raw,db.meta).forEach(t=>{const key=JSON.stringify([t.date,t.customer]);const g=groups[key]||(groups[key]={date:t.date,customer:t.customer,nama:t.nama,rows:[],qty:0,amount:0});g.rows.push(t);g.qty+=t.qty;g.amount+=t.amount;});const all=Object.values(groups).sort((a,b)=>b.date.localeCompare(a.date)||a.nama.localeCompare(b.nama));sortRecords_(all,sort,[g=>g.date,g=>g.nama]);const n=Math.min(Math.max(0,Number(page)||0),Math.max(0,Math.ceil(all.length/size)-1));return {rows:all.slice(n*size,n*size+size),total:all.length,page:n,pageSize:size,from,to,totals:{qty:raw.reduce((s,r)=>s+r.qty,0),amount:raw.reduce((s,r)=>s+r.amount,0)}};}
const USER_BULK_HEADERS=['NIK','NAMA','POSISI','REGION','NIK_ATASAN','WILAYAH_ADMIN'];
function userBulkRows_(file){if(!file?.getBytes||!file.getBytes().length||file.getBytes().length>5*1024*1024)throw Error('Pilih XLSX/CSV maksimal 5 MB.');let grid,tmp;try{if(/\.csv$/i.test(file.getName())){const s=file.getDataAsString('UTF-8').replace(/^\uFEFF/,'');grid=Utilities.parseCsv(s,s.split(/\r?\n/)[0].includes(';')?';':',');}else if(/\.xlsx$/i.test(file.getName())){tmp=Drive.Files.create({name:'USER_IMPORT',mimeType:'application/vnd.google-apps.spreadsheet',parents:[folder_().getId()]},file,{fields:'id'}).id;const w=SpreadsheetApp.openById(tmp),sh=w.getSheetByName('Template_User')||w.getSheets()[0];grid=sh.getDataRange().getDisplayValues();}else throw Error('Gunakan XLSX atau CSV.');const ALIAS={'JABATAN':'POSISI','NIK ATASAN':'NIK_ATASAN','WILAYAH ADMIN':'WILAYAH_ADMIN','NIK KARYAWAN':'NIK'},heads=(grid.shift()||[]).map(h=>{const x=PortalCore.text(h).toUpperCase().replace(/\s+/g,' ');return ALIAS[x]||x;});USER_BULK_HEADERS.slice(0,5).forEach(h=>{if(!heads.includes(h))throw Error('Kolom wajib: '+h);});return grid.filter(r=>r.some(v=>PortalCore.text(v))).map(r=>Object.fromEntries(heads.map((h,i)=>[h,PortalCore.text(r[i])])));}finally{if(tmp)DriveApp.getFileById(tmp).setTrashed(true);}}
function validateUserBulk_(rows,db,u){if(!Array.isArray(rows)||!rows.length||rows.length>1000)throw Error('Isi 1–1.000 user per file.');const seen=new Set(),rm=settings_().regions,existing=new Set(db.meta.people.map(p=>p.nik)),out=rows.map((r,i)=>{const nik=PortalCore.text(r.NIK);if(!/^[A-Za-z0-9._-]{2,60}$/.test(nik)||seen.has(nik))throw Error('NIK tidak valid/duplikat pada baris '+(i+2));seen.add(nik);if(existing.has(nik))return {nik,skip:true,nama:'Akun sudah terdaftar',row:r};const role=PortalCore.text(r.POSISI).toUpperCase(),nama=PortalCore.text(r.NAMA),region=PortalCore.text(r.REGION),regionMatch=(rm.find(x=>PortalCore.text(x.REGION).toUpperCase()===PortalCore.text(r.REGION).toUpperCase())||{}).REGION,wilayah=rm.find(x=>PortalCore.text(x.REGION).toUpperCase()===region.toUpperCase())?.WILAYAH_KPI||'',atasan=PortalCore.text(r.NIK_ATASAN),access=PortalCore.text(r.WILAYAH_ADMIN).split('|').map(s=>s.trim()).filter(Boolean);if(!nama||nama.length>120||!(u.role==='SUPER ADMIN'?Object.keys(PortalCore.LEVEL):['SALES','ASM','RGM']).includes(role))throw Error('Nama/jabatan tidak valid: '+nik);if(['SALES','ASM','RGM'].includes(role)&&!wilayah)throw Error('Region belum dipetakan: NIK '+nik+' · REGION "'+region+'" tidak ada di kolom REGION sheet Region_Map (isi region/sub region seperti BIG PURWOKERTO, bukan Big Region seperti JAWA TENGAH). Tambahkan dulu lewat Bulk master > Region Map.');if(u.role!=='SUPER ADMIN'&&!(u.adminRegions||[]).includes(wilayah))throw Error('Region di luar penugasan: '+nik);if(role==='ADMIN'&&(!access.length||access.some(x=>!RegionCore.regions(db.meta).includes(x))))throw Error('Wilayah Admin tidak valid: '+nik);return {nik,nama,role,region:regionMatch||region,wilayah,atasan,access,row:r,skip:false};});const people=db.meta.people.concat(out.filter(r=>!r.skip));out.filter(r=>!r.skip).forEach(r=>{const b=people.find(p=>p.nik===r.atasan);if(['SALES','ASM','RGM'].includes(r.role)&&!r.atasan)throw Error('NIK atasan wajib: '+r.nik);if(r.atasan&&(!b||b.role==='ADMIN'||PortalCore.LEVEL[b.role]<=PortalCore.LEVEL[r.role]||u.role!=='SUPER ADMIN'&&!canManageUser_(u,b)))throw Error('Atasan tidak valid/di luar kewenangan: '+r.nik);});return out;}
function userBulkPartition_(rows,db,u){rows=rows.slice();const rejected=[],fixFor=m=>/Region belum dipetakan/.test(m)?'Tambah region di Admin › Master › Region Map, atau ganti REGION ke region yang ada (bukan Big Region).':/NIK tidak valid/.test(m)?'NIK hanya huruf/angka/titik/strip (2–60 karakter) dan tidak boleh dobel di file.':/Nama\/jabatan/.test(m)?'Isi NAMA, dan JABATAN/POSISI: SALES, ASM, RGM'+(u.role==='SUPER ADMIN'?', ADMIN, HEAD OF SALES, dst.':'.'):/luar penugasan/.test(m)?'Region ini di luar wilayah tugas Anda — minta Super Admin.':/Wilayah Admin/.test(m)?'Isi WILAYAH ADMIN dengan Big Region yang ada, pisahkan dengan |.':/atasan wajib/.test(m)?'Isi NIK ATASAN (ASM untuk Sales, RGM untuk ASM).':/Atasan tidak valid/.test(m)?'NIK ATASAN harus terdaftar (atau ada di file yang sama) dan jabatannya lebih tinggi.':'Perbaiki baris ini lalu upload ulang.';
 for(let guard=0;guard<=1000;guard++){if(!rows.length)return {ok:[],rows:[],rejected};try{return {ok:validateUserBulk_(rows,db,u),rows,rejected};}catch(e){const m=String(e&&e.message||e);let idx=-1;const b=/baris (\d+)/i.exec(m);if(b)idx=+b[1]-2;else{const mm=m.replace(/ · .*/,''),n=/NIK ([A-Za-z0-9._-]{2,60})/.exec(mm)||/: ([A-Za-z0-9._-]{2,60})\s*$/.exec(mm);if(n)idx=rows.findIndex(r=>PortalCore.text(r.NIK)===n[1]);}if(idx<0||idx>=rows.length)throw e;rejected.push({row:rows[idx],alasan:m.replace(/ Tambahkan dulu lewat Bulk master > Region Map\./,''),solusi:fixFor(m)});rows.splice(idx,1);}}throw Error('Terlalu banyak baris salah.');}
function apiStageUsers(form){const db=snapshot_(),u=adminGuard_(form.token,db),all=userBulkRows_(form.file);if(all.length>1000)throw Error('Maksimal 1.000 user per file.');const P=userBulkPartition_(all,db,u),id=Utilities.getUuid();props_().setProperty('USER_STAGE_'+id,writeJson_('user-preview-'+id,{actor:u.nik,base:db.id,config:configHash_(meta_()),created:Date.now(),rows:P.rows,rejected:P.rejected,name:form.file.getName?form.file.getName():'user.xlsx'}));return {id,rejected:P.rejected.length,rejectedSample:P.rejected.slice(0,50).map(x=>({nik:PortalCore.text(x.row.NIK),nama:PortalCore.text(x.row.NAMA),alasan:x.alasan,solusi:x.solusi})),rows:P.ok.map(r=>({nik:r.nik,nama:r.nama,role:r.role||'',region:r.region||'',status:r.skip?'Dilewati (sudah terdaftar)':'User baru'}))};}
function apiUsersRejected(token,id){const db=snapshot_(),u=adminGuard_(token,db),ptr=props_().getProperty('USER_STAGE_'+id);if(!ptr)throw Error('Pratinjau tidak tersedia.');const s=readJson_(ptr);if(s.actor!==u.nik)throw Error('Pratinjau milik user lain.');if(!(s.rejected||[]).length)throw Error('Tidak ada baris ditolak.');const heads=Object.keys(s.rejected[0].row);return rejectBase64_(s.name||'user.xlsx',heads,s.rejected);}
function apiCommitUsers(token,id){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const db=snapshot_(),u=adminGuard_(token,db),ptr=props_().getProperty('USER_STAGE_'+id);if(!ptr)throw Error('Pratinjau sudah dipakai/tidak tersedia.');const stage=readJson_(ptr);if(stage.actor!==u.nik||stage.base!==db.id||stage.config!==configHash_(meta_())||Date.now()-stage.created>3600000)throw Error('Data berubah/pratinjau kedaluwarsa. Periksa file lagi.');if(!(stage.rows||[]).length){props_().deleteProperty('USER_STAGE_'+id);return {created:0,skipped:0,rows:[],download:false};}const all=validateUserBulk_(stage.rows,db,u),rows=all.filter(r=>!r.skip);if(!rows.length){props_().deleteProperty('USER_STAGE_'+id);return {created:0,skipped:all.length,rows:[],download:u.role==='SUPER ADMIN'};}const grids={Master_Sales:readGrid_('Master_Sales'),Admin_Access:readGrid_('Admin_Access'),_Auth:readGrid_('_Auth')},objects=table_('Master_Sales').concat(rows.map(r=>({'NIK KARYAWAN':r.nik,SALES:r.nama,POSISI:r.role,REGION:r.region,'NIK ATASAN':r.atasan})));PortalCore.normalize({sales:objects,customers:table_('Master_Customer'),products:table_('Master_Product')},settings_());checkpoint_(u.nik,'Tambah user massal '+rows.length);try{const heads=grids.Master_Sales[0];putTable_('Master_Sales',heads,objects.map(r=>heads.map(h=>r[h]??'')));const access=optionalTable_('Admin_Access').map(r=>[r.NIK,r.WILAYAH]);rows.filter(r=>r.role==='ADMIN').forEach(r=>r.access.forEach(a=>access.push([r.nik,a])));putTable_('Admin_Access',['NIK','WILAYAH'],access);const result=rows.map(r=>{const pin=randomPin_();setPin_(r.nik,pin,true);return {nik:r.nik,nama:r.nama,role:r.role,region:r.region,pin};});const meta=meta_();validateConfigChange_(db,meta);publish_(meta,db.raw,db.coverage,u.nik,'USER_BULK '+rows.length);props_().deleteProperty('USER_STAGE_'+id);audit_(u.nik,'USER_BULK',String(rows.length));return {created:rows.length,skipped:all.length-rows.length,rows:result,download:u.role==='SUPER ADMIN'};}catch(e){Object.keys(grids).forEach(n=>restoreGrid_(n,grids[n]));throw e;}}finally{lock.releaseLock();}}
function apiDealerStock(token,period,selection,customer){const source=snapshot_(),u=guard_(token,false,false,source),ids=allowed_(source,u,selection);if(!StockCore.canSee(source,ids,customer))throw Error('Dealer di luar cakupan.');const db=coverageView_(source,period,ids,'PAIR',u);if(db.missingST||db.missingSO)return {ready:false,message:'Menunggu kelengkapan ST / SO.'};const r=StockCore.calculate(db,period,ids,{query:customer});if(r.ready)r.rows=r.rows.filter(t=>(t.customer||t.id)===customer);return {ready:r.ready,message:r.message,asof:r.asof,stCut:r.stCut,soCut:r.soCut,rows:r.rows||[]};}

function apiUserTemplate(token){adminGuard_(token);return templateXlsx_('Template-User-Massal.xlsx','Template_User',['NIK','NAMA','POSISI','REGION','NIK_ATASAN','WILAYAH_ADMIN'],[],[]);}
