var CHECKPOINT_SHEETS=['Master_Sales','Master_Customer','Master_Product','Master_Target','Target_Periode','Target_Input','KPI_Config','KPI_RGM','Region_Map','Product_Rules','DOS_Config','Admin_Access','Export_Access','Dealer_Region','Dealer_Assignment_History','Master_Promotor','Master_Grade','Period_Locks','Informasi','_Auth'];
var RegionCore=(function(){
 const top=role=>['HEAD OF SALES','CHIEF OPERATING OFFICER','CHIEF COMMERCIAL OFFICER','BOARD OF DIRECTOR'].includes(role);
 function regions(meta){return [...new Set(meta.people.map(p=>p.wilayah).filter(Boolean).concat(meta.regionList||[]))].sort();}
 function route(db,t,kind){if(t.region)return t.region;const cu=custInduk_(db.meta,t.customer);const edits=(db.meta.dealerRegions||[]).filter(r=>(r.customer===cu||r.customer===t.customer)&&r.from<=t.date).sort((a,b)=>b.from.localeCompare(a.from));if(edits.length)return edits[0].region;return db.routing?.customers?.[cu]||db.routing?.customers?.[t.customer]||(kind==='ST'?db.routing?.sales?.[t.nik]:null);}
 function routing(meta,tx,previous){const result=JSON.parse(JSON.stringify(previous||{customers:{},sales:{}}));meta.people.forEach(p=>{if(p.wilayah&&!result.sales[p.nik])result.sales[p.nik]=p.wilayah;});Object.values(meta.customers).forEach(c=>{if(!result.customers[c.id]&&result.sales[c.nik])result.customers[c.id]=result.sales[c.nik];});const choices={};tx.forEach(t=>{const cu=custInduk_(meta,t.customer);if(result.sales[t.nik])(choices[cu]||(choices[cu]=new Set())).add(result.sales[t.nik]);});Object.keys(choices).forEach(c=>{if(!result.customers[c]&&choices[c].size===1)result.customers[c]=[...choices[c]][0];});return result;}
 function common(parts,kind,period,selected){const entries=selected.map(r=>parts?.[kind]?.[period]?.[r]),cuts=entries.map(e=>e?.cutoff||null);return {cutoff:cuts.every(Boolean)&&cuts.length?cuts.slice().sort()[0]:null,latest:cuts.filter(Boolean).sort().pop()||null,missing:selected.filter((r,i)=>!cuts[i]),rows:selected.map((r,i)=>({region:r,cutoff:cuts[i]}))};}
 function replace(parts,kind,period,selected,incoming){const out=JSON.parse(JSON.stringify(parts));out[kind]=out[kind]||{};out[kind][period]=out[kind][period]||{};selected.forEach(r=>{if(!incoming[r])throw Error('Region belum memiliki deklarasi data: '+r);out[kind][period][r]=incoming[r];});return out;}
 function sliceFor(db,period,ids,kind){const selected=[...new Set(db.meta.people.filter(p=>ids.includes(p.nik)).flatMap(p=>p.role==='ADMIN'?(p.adminRegions||[]):[p.wilayah]).filter(Boolean))];if(db.meta.people.every(p=>ids.includes(p.nik)))return regions(db.meta);return selected;}
 return {top,regions,route,routing,common,replace,sliceFor};
})();
function optionalTable_(name){return book_().getSheetByName(name)?table_(name):[];}
function adminGuard_(token,db){const u=guard_(token,false,false,db);if(!['ADMIN','SUPER ADMIN'].includes(u.role))throw Error('Akses admin diperlukan.');return u;}
function canManageUser_(actor,target){return actor.role==='SUPER ADMIN'||actor.role==='ADMIN'&&['SALES','ASM','RGM'].includes(target.role)&&(actor.adminRegions||[]).includes(target.wilayah);}
function enforceUser_(token,nik){const db=snapshot_(),u=adminGuard_(token,db),target=db.meta.people.find(p=>p.nik===nik);if(!target||!canManageUser_(u,target))throw Error('User di luar kewenangan atau jabatan terlindungi.');return {u,target,db};}
function revokeAll_(){Object.keys(props_().getProperties()).filter(k=>k.startsWith('SESSION_')).forEach(k=>props_().deleteProperty(k));}
function assertPeriodOpen_(period){if(PortalCore.active(optionalTable_('Period_Locks').find(r=>r.PERIODE===period)?.TERKUNCI))throw Error('Periode dikunci. Super Admin perlu membuka dengan alasan.');}
function checkpoint_(actor,reason){const id=props_().getProperty('ACTIVE');const sheets={};CHECKPOINT_SHEETS.forEach(n=>{const sh=book_().getSheetByName(n);if(sh)sheets[n]=sh.getDataRange().getValues();});const file=writeJson_('before-'+Date.now(),{active:id,sheets,at:new Date().toISOString(),actor,reason});audit_(actor,'CHECKPOINT',reason+' '+file);return file;}
function upgradeV4_(){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const old=snapshot_();checkpoint_('EDITOR','Upgrade v4');ensureTable_('Admin_Access',['NIK','WILAYAH'],[]);ensureTable_('Dealer_Region',['KODE CUSTOMER','WILAYAH','BERLAKU_MULAI'],[]);ensureTable_('Dealer_Assignment_History',['KODE CUSTOMER','NIK SALES','BERLAKU_MULAI','BERLAKU_SAMPAI','SUMBER','NOTE','UPDATED_BY','UPDATED_AT'],[]);ensureTable_('Period_Locks',['PERIODE','TERKUNCI','ALASAN','OLEH','WAKTU'],[]);ensureTable_('Backup_Log',['WAKTU','JENIS','STATUS','FOLDER','KETERANGAN'],[]);ensureTable_('Version_Log',['WAKTU','AKTOR','ALASAN','SNAPSHOT'],[]);ensureTable_('DOS_Config',['WILAYAH','DOS_MIN','DOS_MAX'],[['ALL',7,45]]);ensureInfo_();ensureColumns_('Informasi',['WILAYAH_LIST','ROLE_LIST']);ensureColumns_('KPI_Config',['INDIKATOR_ID','LABEL','TYPE_FILTER','MIN_QTY_DA']);ensureColumns_('Target_Periode',['INDIKATOR_ID']);const r=publish_(meta_(),old.raw,old.coverage,'EDITOR','Upgrade v4');props_().setProperty('APP_SCHEMA','4');revokeAll_();SpreadsheetApp.getUi().alert('Upgrade v4 selesai. Deploy versi baru dan login ulang. Pasang autobackup melalui menu spreadsheet.');return r;}finally{lock.releaseLock();}}

function ensureColumns_(name,columns){const grid=readGrid_(name);if(!grid)throw Error("Sheet tidak ditemukan: "+name);const heads=grid[0].map(String),extra=columns.filter(h=>!heads.includes(h));if(extra.length)putTable_(name,heads.concat(extra),grid.slice(1).map(r=>r.concat(extra.map(()=>""))));}
