function stReadFile_(file){
 if(!file?.getBytes||file.getBytes().length>5*1024*1024)throw Error('Pilih XLSX/CSV maksimal 5 MB.');let data,tmp;try{const name=file.getName();if(/\.csv$/i.test(name)){const s=file.getDataAsString('UTF-8').replace(/^\uFEFF/,''),line=s.split(/\r?\n/)[0];data=Utilities.parseCsv(s,line.split(';').length>line.split(',').length?';':',');}else if(/\.xlsx$/i.test(name)){tmp=Drive.Files.create({name:'ST_IMPORT',mimeType:'application/vnd.google-apps.spreadsheet',parents:[folder_().getId()]},file,{fields:'id'}).id;const w=SpreadsheetApp.openById(tmp);w.setSpreadsheetTimeZone('Asia/Jakarta');const sh=w.getSheetByName('Master_Transaksi')||(w.getSheets().length===1?w.getSheets()[0]:null);if(!sh)throw Error('Sheet Master_Transaksi tidak ditemukan.');data=sh.getDataRange().getValues();}else throw Error('Format XLSX atau CSV.');const heads=data.shift().map(PortalCore.text);['TANGGAL TRANSAKSI','NO TRANSAKSI','KODE PRODUK','KODE CUSTOMER','NIK SALES','QTY','AMOUNT'].forEach(k=>{if(!heads.includes(k))throw Error('Kolom wajib '+k);});return data.filter(r=>r.some(v=>v!==''&&v!=null)).map(r=>Object.fromEntries(heads.map((k,i)=>[k,r[i] instanceof Date?Utilities.formatDate(r[i],'Asia/Jakarta','yyyy-MM-dd'):r[i]])));}finally{if(tmp)DriveApp.getFileById(tmp).setTrashed(true);}}
function parseRegions_(value,meta){let list;try{list=JSON.parse(String(value||'[]'));}catch(e){throw Error('Pilihan region tidak valid.');}const known=RegionCore.regions(meta);if(!Array.isArray(list)||!list.length||list.some(r=>typeof r!=='string'||!known.includes(r)))throw Error('Pilih big region yang sah.');return [...new Set(list)];}
function parseImportBrands_(value,meta){let list;try{list=JSON.parse(String(value||'[]'));}catch(e){throw Error('Pilihan brand tidak valid.');}const known=[...new Set(Object.values(meta.products||{}).filter(p=>p.device).map(p=>p.brand).filter(Boolean))].sort();if(!Array.isArray(list)||!list.length)return [];list=[...new Set(list.map(PortalCore.text).filter(Boolean))];if(list.some(b=>!known.includes(b)))throw Error('Brand upload tidak dikenal: '+list.filter(b=>!known.includes(b)).join(', '));return list;}
function importBrand_(t,meta,kind){return PortalCore.text(t.brand)||PortalCore.text(meta.products?.[t.sku]?.brand);}
function stageRegionImport_(form,kind){const u=adminGuard_(form.token),old=snapshot_(),meta=meta_();if(!old.parts)throw Error('Jalankan Upgrade v4 terlebih dahulu.');const regions=parseRegions_(form.regions,meta),brands=parseImportBrands_(form.brands,meta),period=PortalCore.month(form.period),cutoff=PortalCore.iso(form.cutoff),history=kind==='SO'&&form.mode==='HISTORY';if(cutoff.slice(0,7)!==period)throw Error('Cutoff berbeda bulan.');assertPeriodOpen_(period);if(history&&cutoff<StockCore.BASE)throw Error('Histori awal minimal Desember 2025.');if(history&&brands.length)throw Error('Mode histori awal SO harus menggunakan Semua Brand.');
 let empty=[];try{empty=JSON.parse(String(form.emptyRegions||'[]'));}catch(e){throw Error('Deklarasi region kosong tidak valid.');}if(!Array.isArray(empty)||empty.some(r=>!regions.includes(r)))throw Error('Deklarasi kosong di luar pilihan.');const objects=form.file?.getName?.()?kind==='ST'?stReadFile_(form.file):soReadFile_(form.file):[];
 const rm=kind==='ST'?stRemapNik_(objects,meta):{count:0,note:''};
 const rows=kind==='ST'?PortalCore.transactions(objects,meta,period,cutoff):StockCore.parse(objects,meta,history?null:period,cutoff),routing=RegionCore.routing(meta,Object.keys(old.raw).flatMap(p=>readJson_(old.raw[p])),old.routing),shell={meta,routing};if(rows.length>150000)throw Error('Maksimal 150.000 baris per impor.');const by={},warnings=[];if(rm.count)warnings.push(rm.note);
 rows.forEach((t,i)=>{const region=RegionCore.route(shell,t,kind),brand=importBrand_(t,meta,kind);if(!region||!regions.includes(region))throw Error('Baris '+(i+2)+': dealer '+t.customer+' masuk '+(region||'region belum terpetakan')+', di luar pilihan.');if(brands.length&&!brands.includes(brand))throw Error('Baris '+(i+2)+': brand '+(brand||'tidak dikenal')+' di luar brand upload '+brands.join(', ')+'.');t.region=region;(by[region]||(by[region]=[])).push(t);});
 regions.forEach(r=>{if(!by[r]?.length&&!empty.includes(r))throw Error('Region '+r+' tidak memiliki baris. Nyatakan nol secara eksplisit.');if(by[r]?.length&&empty.includes(r))throw Error('Region '+r+' dinyatakan kosong tetapi ada data.');});
 const months=history?[...new Set(rows.map(t=>t.date.slice(0,7)).concat(monthSequence_(StockCore.BASE.slice(0,7),period)))]:[period];months.forEach(p=>assertPeriodOpen_(p));if(history&&regions.some(r=>Object.values(old.parts.SO||{}).some(m=>m[r])))throw Error('Histori SO region ini sudah ada. Gunakan penggantian bulanan.');
 const controls=regions.map(r=>{const entry=old.parts[kind]?.[period]?.[r],oldRows=entry?readJson_(entry.file):[],beforeRows=brands.length?oldRows.filter(t=>brands.includes(importBrand_(t,meta,kind))):oldRows,incomingRows=by[r]||[],incoming=summarySO_(incomingRows),before=summarySO_(beforeRows);if(entry&&cutoff<entry.cutoff)warnings.push(r+': cutoff mundur dari '+entry.cutoff);if(before.qty>0&&incoming.qty<before.qty*.7)warnings.push(r+': QTY scope upload turun lebih dari 30%; periksa sumber.');return {region:r,before,incoming,oldCutoff:entry?.cutoff||null};});if(history)warnings.push('Histori awal menyatakan seluruh bulan sejak Desember 2025 lengkap untuk region pilihan.');if(brands.length)warnings.push('Upload parsial brand: hanya '+brands.join(', ')+' yang diganti; brand lain pada region pilihan dipertahankan.');
 const id=Utilities.getUuid(),stage={kind,actor:u.nik,base:old.id,config:configHash_(meta),created:Date.now(),regions,brands,period,cutoff,history,months,rows};adminGuard_(form.token);props_().setProperty('REGION_STAGE_'+id,writeJson_('stage-region-'+id,stage));return {id,kind,period,cutoff,history,brands,controls,warnings};}
function monthSequence_(from,to){const out=[];for(let d=from+'-01';d<=to+'-01';d=StockCore.shift(PortalCore.end(d.slice(0,7)),1))out.push(d.slice(0,7));return out;}
function summarySO_(rows){return {rows:rows.length,qty:rows.reduce((n,r)=>n+r.qty,0),amount:PortalCore.round(rows.reduce((n,r)=>n+(r.amount||0),0))};}
function publishRegionImport_(token,id){const u=adminGuard_(token),lock=LockService.getScriptLock();lock.waitLock(10000);try{adminGuard_(token);const pointer=props_().getProperty('REGION_STAGE_'+String(id));if(!pointer)throw Error('Pratinjau tidak tersedia.');const s=readJson_(pointer),old=snapshot_(),meta=meta_();if(s.actor!==u.nik||s.base!==old.id||s.config!==configHash_(meta)||Date.now()-s.created>3600000)throw Error('Pratinjau kedaluwarsa atau data berubah; periksa ulang.');s.months.forEach(assertPeriodOpen_);const scope=s.brands?.length?' ['+s.brands.join(', ')+']':'';checkpoint_(u.nik,'Impor '+s.kind+' '+s.regions.join(', ')+scope);let parts=old.parts;s.months.forEach(p=>{const incoming={};s.regions.forEach(r=>{const selected=s.rows.filter(t=>t.region===r&&t.date.slice(0,7)===p),currentEntry=parts?.[s.kind]?.[p]?.[r],current=currentEntry?readJson_(currentEntry.file):[],merged=s.brands?.length?current.filter(t=>!s.brands.includes(importBrand_(t,meta,s.kind))).concat(selected):selected;incoming[r]={file:writeJson_(s.kind+'-'+p+'-'+r+'-'+Date.now(),merged),cutoff:p===s.period?s.cutoff:PortalCore.end(p)};});parts=RegionCore.replace(parts,s.kind,p,s.regions,incoming);});const result=publish_(meta,old.raw,old.coverage,u.nik,s.kind+' '+s.period+' '+s.regions.join(', ')+scope,null,parts);props_().deleteProperty('REGION_STAGE_'+id);return result;}finally{lock.releaseLock();}}
function coverageView_(db,period,ids,kind,actor){
 const selected=RegionCore.sliceFor(db,period,ids,kind).filter(r=>actor?.role!=='ADMIN'||(actor.adminRegions||[]).includes(r));
 const view={...db,coverage:{},stock:db.stock?{...db.stock,coverage:{},moves:db.stock.moves.filter(t=>!t.region||selected.includes(t.region))}:null,cubes:{}};if(!db.parts)return db;
 for(const p of Object.keys(db.coverage)){const st=RegionCore.common(db.parts,'ST',p,selected),so=RegionCore.common(db.parts,'SO',p,selected),stC=st.cutoff||st.latest,soC=so.cutoff||so.latest,cut=kind==='PAIR'&&stC&&soC?[stC,soC].sort()[0]:stC;
 if(cut)view.coverage[p]={cutoff:cut,closed:!!st.cutoff&&cut===PortalCore.end(p)};
 view.cubes[p]=(db.cubes[p]||[]).filter(t=>(!t.region||selected.includes(t.region))&&cut&&t.date<=cut);
 if(view.stock&&soC)view.stock.coverage[p]={cutoff:kind==='PAIR'&&stC?[stC,soC].sort()[0]:soC};
 if(p===period){view.partial=!st.cutoff||(kind==='PAIR'&&!so.cutoff)||!!cut&&cut!==PortalCore.end(p);view.missingST=!stC;view.missingSO=!soC;view.partialST=!st.cutoff&&!!stC;view.partialSO=!so.cutoff&&!!soC;view.missingRegionsST=selected.filter(r=>!db.parts.ST?.[p]?.[r]);view.missingRegionsSO=selected.filter(r=>!db.parts.SO?.[p]?.[r]);view.regionStatus=selected.map(r=>({region:r,st:db.parts.ST?.[p]?.[r]?.cutoff||null,so:db.parts.SO?.[p]?.[r]?.cutoff||null}));}
 }
 if(!view.coverage[period]){view.coverage[period]={cutoff:period+'-01',closed:false};view.noData=true;view.missingST=true;view.partial=true;view.regionStatus=selected.map(r=>({region:r,st:null,so:db.parts.SO?.[period]?.[r]?.cutoff||null}));}view.selectedRegions=selected;view.historyComplete=monthSequence_(StockCore.BASE.slice(0,7),period).every(p=>{const c=RegionCore.common(db.parts,'ST',p,selected);return c.cutoff&&c.cutoff>=(p===period?view.coverage[p]?.cutoff:PortalCore.end(p));});return view;
}
function revokeChanged_(before,after){const changed=before.filter(p=>JSON.stringify(p)!==JSON.stringify(after.find(x=>x.nik===p.nik))).map(p=>p.nik);const all=props_().getProperties();Object.keys(all).filter(k=>k.startsWith('SESSION_')).forEach(k=>{try{if(changed.includes(JSON.parse(all[k]).nik))props_().deleteProperty(k);}catch(e){props_().deleteProperty(k);}});}
function validateConfigChange_(old,meta){rgmRuleCheck_(old.meta,meta);const activeSuper=meta.people.filter(p=>p.role==='SUPER ADMIN'&&PortalCore.active(account_(p.nik)?.AKTIF));if(!activeSuper.length)throw Error('Harus ada Super Admin aktif.');const last=Object.values(old.coverage).map(v=>v.cutoff).sort().pop();(meta.dealerRegions||[]).forEach(r=>{const existed=(old.meta.dealerRegions||[]).some(x=>JSON.stringify(x)===JSON.stringify(r));if(!existed&&r.from<=last)throw Error('Mapping dealer baru harus efektif setelah cutoff publikasi '+last);});(old.meta.dealerRegions||[]).forEach(r=>{if(!meta.dealerRegions.some(x=>JSON.stringify(x)===JSON.stringify(r)))throw Error('Riwayat mapping tidak boleh dihapus/diubah; tambahkan tanggal efektif baru.');});}
