function soReadFile_(file){
 if(!file||!file.getBytes||file.getBytes().length>5*1024*1024)throw Error('Pilih XLSX/CSV maksimal 5 MB.');let data,tmp;
 try{const name=file.getName();if(/\.csv$/i.test(name)){const s=file.getDataAsString('UTF-8').replace(/^\uFEFF/,''),line=s.split(/\r?\n/)[0];data=Utilities.parseCsv(s,line.split(';').length>line.split(',').length?';':',');}
 else if(/\.xlsx$/i.test(name)){tmp=Drive.Files.create({name:'SO_IMPORT_'+Date.now(),mimeType:'application/vnd.google-apps.spreadsheet',parents:[folder_().getId()]},file,{fields:'id'}).id;const book=SpreadsheetApp.openById(tmp);book.setSpreadsheetTimeZone('Asia/Jakarta');const sheet=book.getSheetByName('Master_SO')||(book.getSheets().length===1?book.getSheets()[0]:null);if(!sheet)throw Error('Pilih sheet Master_SO atau workbook satu sheet.');data=sheet.getDataRange().getValues();}else throw Error('Format harus XLSX/CSV.');
 const heads=data.shift().map(PortalCore.text);['KODE CUSTOMER','TANGGAL SO','KODE PRODUK','QTY'].forEach(h=>{if(!heads.includes(h))throw Error('Kolom SO wajib: '+h);});if(new Set(heads).size!==heads.length)throw Error('Header SO berulang.');return data.filter(r=>r.some(v=>v!==''&&v!=null)).map(r=>{const o={};heads.forEach((h,i)=>o[h]=r[i] instanceof Date?Utilities.formatDate(r[i],'Asia/Jakarta','yyyy-MM-dd'):r[i]);return o;});
 }finally{if(tmp)DriveApp.getFileById(tmp).setTrashed(true);}
}
function dosRules_(){if(!book_().getSheetByName('DOS_Config'))return [{region:'ALL',min:7,max:45}];const seen=new Set();return table_('DOS_Config').map(r=>{const region=PortalCore.text(r.WILAYAH),min=PortalCore.number(r.DOS_MIN),max=PortalCore.number(r.DOS_MAX);if(!region||seen.has(region)||min<0||max<=min)throw Error('DOS_Config: wilayah unik, DOS_MIN >= 0 dan DOS_MAX > DOS_MIN.');seen.add(region);return {region,min,max};});}
function apiStageSO(form){return stageRegionImport_(form,'SO');}
function apiPublishSO(token,id){return publishRegionImport_(token,id);}
function apiDOS(token,period,selection,filter,page){const source=snapshot_(),u=guard_(token,false,false,source),ids=(function(){const on=onlineSet_(),pp={};source.meta.people.forEach(p=>{pp[p.nik]=p;});return allowed_(source,u,selection).filter(n=>!isOnlinePerson_(pp[n],on));})(),db=coverageView_(source,period,ids,'PAIR',u),f=filter&&typeof filter==='object'?filter:{},size=[50,100,200].includes(Number(f.pageSize))?Number(f.pageSize):100;if(db.missingST||db.missingSO)return {ready:false,message:'Menunggu ST dan SO seluruh region dalam pilihan. Pilih cakupan lebih kecil.',regionStatus:db.regionStatus};const top=RegionCore.top(u.role),ck=dosCacheKey_(source,period,ids,f,top);let r=dosCacheGet_(ck);if(!r){r=StockCore.calculate(db,period,ids,f);r.regionStatus=db.regionStatus||[];if(top&&r.ready)r.regions=aggregateBigDOS_(r);dosCachePut_(ck,r);}if(!r.ready)return r;if(f.view==='BRAND')sortRecords_(r.brands,f.sort,[t=>t.nama,t=>t.brand,t=>t.stock,t=>t.sellout,t=>t.avg,t=>t.dos,t=>t.low]);else sortRecords_(r.rows,f.sort,[t=>t.nama,t=>t.sales,t=>t.brand,t=>t.type,t=>t.stock,t=>t.sellout,t=>t.avg,t=>t.dos,t=>t.status]);const count=f.view==='BRAND'?r.brands.length:r.rows.length,n=Math.min(Math.max(0,Math.floor(Number(page)||0)),Math.max(0,Math.ceil(count/size)-1));r.count=count;r.page=n;r.pageSize=size;r.rows=r.rows.slice(n*size,n*size+size);if(u.role==='SALES')r.regions=[];return r;}
function upgradeV3_(){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const old=snapshot_();upgradeRoles_();ensureInfo_();ensureTable_('DOS_Config',['WILAYAH','DOS_MIN','DOS_MAX'],[['ALL',7,45]]);publish_(meta_(),old.raw,old.coverage,'EDITOR','Upgrade v3 DOS/SO');props_().setProperty('APP_SCHEMA','3');SpreadsheetApp.getUi().alert('Upgrade v3 selesai. Target/PIN/ST tetap. Deploy versi baru, lalu Admin → Impor Sell Out → Histori awal.');}finally{lock.releaseLock();}}
